'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
function load(file,deps={},globals={}){const c={module:{exports:{}},console:{warn(){},error(){}},Buffer,Date,Map,Set,AbortSignal,URL,process:{env:{SESSION_SECRET:'a-test-secret-that-stays-stable'}},fetch:async()=>{throw new Error('unexpected network')},...globals,require:id=>id.endsWith('access-control')?{checkToolAccess:async()=>{}}:id in deps?deps[id]:require(id)};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),c);return c.module.exports;}
const secrets=()=>load('utils/connection-secrets.js');
test('new keys and tokens encrypted, round-trip and tampering rejected',()=>{const s=secrets(),cipher=s.seal({key:'user-private-key'});assert(!cipher.includes('user-private-key'));assert.equal(s.unseal(cipher).key,'user-private-key');const p=cipher.split('.');const b=Buffer.from(p[2],'base64');b[0]^=1;p[2]=b.toString('base64');assert.throws(()=>s.unseal(p.join('.')));});
test('sender selection is scoped to owner and rejects foreign account',async()=>{const calls=[];const api=load('utils/gmail-accounts.js',{'./db':{get:async(sql,args)=>{calls.push({sql,args});return sql.startsWith('SELECT google_id')?{google_id:'primary',active_gmail_id:'own'}:null},run(){}},'./connection-secrets':secrets()});await assert.rejects(api.resolveAccount('user-a','user-b-account'));assert(calls[1].sql.includes('user_id=$2'));assert.equal(calls[1].args[1],'user-a');assert.equal(calls[1].args[0],'user-b-account');});
test('scheduled sender resolves pinned account instead of current selection',async()=>{const s=secrets(),calls=[];const api=load('utils/gmail-accounts.js',{'./db':{get:async(sql,args)=>{calls.push(args);return sql.startsWith('SELECT google_id')?{google_id:'primary',active_gmail_id:'new-choice'}:{id:'scheduled-choice',user_id:'u',email:'old@example.com',credentials:s.seal({access_token:'token'})}},run(){}},'./connection-secrets':s});const account=await api.resolveAccount('u','scheduled-choice');assert.equal(account.gmail_account_id,'scheduled-choice');assert.equal(calls[1][0],'scheduled-choice');});
test('Gemini discovery pages and only includes generateContent models',async()=>{let pages=0;const api=load('utils/ai-providers.js',{'./db':{},'./connection-secrets':{}},{fetch:async(url,opts)=>{assert.equal(opts.headers['x-goog-api-key'],'key');pages++;return {ok:true,json:async()=>pages===1?{models:[{name:'models/embed',supportedGenerationMethods:['embedContent']},{name:'models/text',supportedGenerationMethods:['generateContent']}],nextPageToken:'next'}:{models:[{name:'models/text-2',supportedGenerationMethods:['generateContent']}]}}}});const models=await api.listModels('gemini','key');assert.equal(pages,2);assert.equal(models.length,2);assert(models.every(m=>m.id.startsWith('text')));});
test('OpenRouter free filter excludes paid models unless explicit choice',async()=>{const api=load('utils/ai-providers.js',{'./db':{},'./connection-secrets':{}},{fetch:async(url)=>({ok:true,json:async()=>url.endsWith('/key')?{data:{}}:{data:[{id:'paid',pricing:{prompt:'1',completion:'2'}},{id:'zero:free',pricing:{prompt:'0',completion:'0'}}]}})});const free=await api.listModels('openrouter','key',true);assert(!free.some(m=>m.id==='paid'));assert(free.some(m=>m.id==='zero:free'));assert((await api.listModels('openrouter','key',false)).some(m=>m.id==='paid'));});
test('personal AI fallback tries selected models and validates output',async()=>{const urls=[];const api=load('utils/ai-providers.js',{'./db':{all:async(sql,args)=>{assert.equal(args[0],'owner');return [{provider:'groq',credentials:'encrypted',selected_models:['first','second']}] }},'./connection-secrets':{unseal:()=>({key:'secret'})}},{fetch:async(url,opts)=>{urls.push(JSON.parse(opts.body).model);return {ok:true,json:async()=>({choices:[{message:{content:urls.length===1?'invalid':'{"body":"ok"}'},finish_reason:'stop'}]})}}});const text=await api.callUserAI('owner','prompt',1200,t=>t.startsWith('{'));assert.equal(text,'{"body":"ok"}');assert.equal(urls.join(','),'first,second');});
test('no enabled personal models delegates to existing server chain',async()=>{const api=load('utils/ai-providers.js',{'./db':{all:async()=>[]},'./connection-secrets':{} });assert.equal(await api.callUserAI('u','prompt',100),null);});
test('provider URLs allowlist rejects arbitrary remote address',async()=>{const api=load('utils/ai-providers.js',{'./db':{},'./connection-secrets':{}});await assert.rejects(api.listModels('http://127.0.0.1','key'));});
function authHarness(){const routes=[];const router={get:(name,...handlers)=>routes.push({name,handlers})};let tokenCalls=0,insertCalls=0,savedOwner=null;const api=load('routes/auth.js',{'express':{Router:()=>router},'uuid':{v4:()=> 'new-user'},'../utils/gmail':{getAuthUrl:state=>'google:'+state,getTokensFromCode:async()=>{tokenCalls++;return {access_token:'token',refresh_token:'refresh'}},getUserInfo:async()=>({id:'second-google',email:'second@example.com'})},'../utils/db':{get:async()=>null,run:async()=>{insertCalls++;}},'../utils/gmail-accounts':{saveAccount:async(owner)=>savedOwner=owner},'../middleware/async-handler':fn=>async(req,res)=>fn(req,res),'../middleware/auth':{requireAuth(){}}});return {async callback(req){let redirect;const res={redirect:u=>redirect=u};await routes.find(r=>r.name==='/google/callback').handlers[0](req,res);return redirect;},calls:()=>({tokenCalls,insertCalls,savedOwner})};}
function session(flow){return {userId:'original-user',googleFlow:flow,save:cb=>cb()};}
test('OAuth linking keeps original user and does not create new identity',async()=>{const h=authHarness(),state='valid-state';const result=await h.callback({query:{state,code:'code'},session:session({state,mode:'link',userId:'original-user',expires:Date.now()+10000})});assert.equal(result,'/?linked=gmail');assert.equal(h.calls().savedOwner,'original-user');assert.equal(h.calls().insertCalls,0);});
test('OAuth mismatch rejected before tokens or database changes',async()=>{const h=authHarness();const result=await h.callback({query:{state:'attacker',code:'code'},session:session({state:'expected',mode:'link',userId:'original-user',expires:Date.now()+10000})});assert.equal(result,'/?error=auth_state');assert.equal(h.calls().tokenCalls,0);});
test('UI loads assistant and connection assets and sender is sent in both send paths',()=>{const html=fs.readFileSync(path.join(__dirname,'../public/index.html'),'utf8');for(const file of ['support.js','support.css','connections.js','connections.css'])assert(html.includes('/assets/'+file));assert(fs.readFileSync(path.join(__dirname,'../public/assets/app.js'),'utf8').includes('senderAccountId:gmailActiveId')); assert(html.includes('id="gmail-accounts"'));assert(html.includes('id="ai-providers"'));});
test('OpenAI uses Responses API, max_output_tokens and disables storage',async()=>{let requested;const api=load('utils/ai-providers.js',{'./db':{},'./connection-secrets':{}},{fetch:async(url,opts)=>{requested={url,body:JSON.parse(opts.body)};return {ok:true,json:async()=>({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'OK'}]}]})}}});assert.equal(await api.generate('openai','key','gpt-example','hello',400),'OK');assert(requested.url.endsWith('/responses'));assert.equal(requested.body.max_output_tokens,400);assert.equal(requested.body.store,false);});
test('scheduled email route persists sender selected when scheduling',async()=>{const routes=[],writes=[];const router={post:(name,...handlers)=>routes.push({name,handlers}),get(){},delete(){}};load('routes/email.js',{'express':{Router:()=>router},'uuid':{v4:()=> 'job-id'},'../middleware/auth':{requireAuth(){}},'../middleware/async-handler':fn=>fn,'../utils/db':{get:async(sql)=>sql.includes('FROM companies')?{id:'c',name:'Company',email:'to@example.com'}:sql.includes('FROM users')?{id:'owner'}:null,run:async(sql,args)=>{writes.push({sql,args});return {rowCount:1}}},'../utils/ai':{},'../utils/gmail':{},'../utils/replyTracker':{},'../utils/whatsapp':{},'../utils/gmail-accounts':{resolveAccount:async(owner,id)=>{assert.equal(owner,'owner');assert.equal(id,'selected');return {gmail_account_id:id,email:'sender@example.com'}}}});let result;await routes.find(r=>r.name==='/send').handlers.at(-1)({session:{userId:'owner'},body:{companyId:'c',senderAccountId:'selected',subject:'Title',body:'Body',scheduledAt:new Date(Date.now()+3600000).toISOString()}},{json:r=>result=r,status(){return this}});const job=writes.find(w=>w.sql.startsWith('INSERT INTO scheduled_jobs'));assert.equal(job.args[5],'selected');assert.equal(result.status,'scheduled');assert(writes.some(w=>w.sql.includes('sender_email')&&w.args[1]==='sender@example.com'));});
test('scheduler sends with pinned Gmail account and user AI preferences',async()=>{let tick,sent,owner,selected;const writes=[];const api=load('utils/scheduler.js',{'node-cron':{schedule:(pattern,fn)=>{if(pattern==='* * * * *')tick=fn;return {stop(){}}}},'uuid':{v4:()=> 'log'},'./db':{all:async()=>[{id:'job',user_id:'u',company_id:'c',company_name:'Co',company_email:'to@example.com',sender_account_id:'pinned'}],get:async(sql)=>sql.includes('FROM users')?{id:'u'}:sql.includes('cv_profiles')?{content:'CV'}:null,run:async(sql,args)=>{writes.push({sql,args});return {rowCount:1}}},'./ai':{generateEmail:async args=>{assert.equal(args.userId,'u');return {subject:'Subject',body:'Body'}}},'./gmail':{sendEmail:async args=>{sent=args;return {messageId:'msg',threadId:'thread'}}},'./gmail-accounts':{resolveAccount:async(u,id)=>{owner=u;selected=id;return {gmail_account_id:id,email:'sender@example.com'}}},'./whatsapp':{},'./replyTracker':{}} ,{console:{log(){},error(){}}});api.startScheduler();await tick();assert.equal(owner,'u');assert.equal(selected,'pinned');assert.equal(sent.account.gmail_account_id,'pinned');assert(writes.some(w=>w.sql.includes('sender_email')&&w.args[0]==='pinned'));});
test('bootstrap waits for deferred connection script before loading account',()=>{const html=fs.readFileSync(path.join(__dirname,'../public/index.html'),'utf8');assert(fs.readFileSync(path.join(__dirname,'../public/assets/workspace.js'),'utf8').includes("document.addEventListener('DOMContentLoaded',checkAuth,{once:true})"));});
test('OpenRouter embedded errors preserve rate-limit status without leaking provider data',async()=>{
 const api=load('utils/ai-providers.js',{'./db':{},'./connection-secrets':{}},{fetch:async()=>({ok:true,status:200,json:async()=>({error:{code:429,message:'private CV and secret'}})})});
 await assert.rejects(api.generate('openrouter','secret','openrouter/free','private CV'),e=>e.code==='RATE_LIMIT'&&e.status===429&&!e.message.includes('private'));
});
test('failed output validation has an explicit safe diagnostic with model name',async()=>{
 const logs=[];const api=load('utils/ai-providers.js',{'./db':{all:async()=>[{provider:'openrouter',credentials:'encrypted',selected_models:['openrouter/free']}]},'./connection-secrets':{unseal:()=>({key:'secret-key'})}},{console:{warn:(...args)=>logs.push(args.join(' '))},fetch:async()=>({ok:true,json:async()=>({choices:[{message:{content:'private invalid response'},finish_reason:'stop'}]})})});
 await assert.rejects(api.callUserAI('u','private CV',100,()=>false),e=>e.message.includes('openrouter/free')&&e.message.includes('تنسيقه')&&!e.message.includes('private'));
 assert(logs[0].includes('FORMAT'));assert(!logs[0].includes('secret-key'));assert(!logs[0].includes('private'));
});
test('rejected key skips remaining models on that platform and still tries another',async()=>{
 const used=[];const api=load('utils/ai-providers.js',{'./db':{all:async()=>[{provider:'openrouter',credentials:'encrypted',selected_models:['a','b']},{provider:'groq',credentials:'encrypted',selected_models:['c']}]},'./connection-secrets':{unseal:()=>({key:'secret'})}},{fetch:async(url,opts)=>{used.push(JSON.parse(opts.body).model);return url.includes('openrouter')?{ok:false,status:401,json:async()=>({error:{code:401}})}:{ok:true,json:async()=>({choices:[{message:{content:'OK'},finish_reason:'stop'}]})}}});
 assert.equal(await api.callUserAI('u','p',100),'OK');assert.equal(used.join(','),'a,c');
});
test('truncated and timed-out generation have different reasons',async()=>{
 const deps={'./db':{},'./connection-secrets':{}};
 const truncated=load('utils/ai-providers.js',deps,{fetch:async()=>({ok:true,json:async()=>({choices:[{message:{content:''},finish_reason:'length'}]})})});
 await assert.rejects(truncated.generate('openrouter','k','m','p'),e=>e.code==='TRUNCATED');
 const timed=load('utils/ai-providers.js',deps,{fetch:async()=>{const e=new Error('secret');e.name='TimeoutError';throw e}});
 await assert.rejects(timed.generate('openrouter','k','m','p'),e=>e.code==='TIMEOUT');
});
test('generation gets 40s by default while model discovery retains 20s',async()=>{
 const deadlines=[];const api=load('utils/ai-providers.js',{'./db':{},'./connection-secrets':{}},{AbortSignal:{timeout:ms=>{deadlines.push(ms);return {aborted:false}}},fetch:async url=>({ok:true,json:async()=>url.endsWith('/chat/completions')?{choices:[{message:{content:'OK'},finish_reason:'stop'}]}:url.endsWith('/key')?{data:{}}:{data:[]}})});
 await api.generate('openrouter','key','openrouter/free','p');await api.listModels('openrouter','key');
 assert.equal(deadlines.join(','),'40000,20000,20000');
});
test('runtime timeout overrides are bounded and invalid values revert to defaults',async()=>{
 async function deadline(value){let ms;const api=load('utils/ai-providers.js',{'./db':{},'./connection-secrets':{}},{process:{env:{AI_MODEL_TIMEOUT_MS:value}},AbortSignal:{timeout:value=>{ms=value;return {aborted:false}}},fetch:async()=>({ok:true,json:async()=>({choices:[{message:{content:'OK'},finish_reason:'stop'}]})})});await api.generate('openrouter','k','m','p');return ms;}
 assert.equal(await deadline('50000'),50000);assert.equal(await deadline('999999'),40000);assert.equal(await deadline('bad'),40000);
});
