'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const channels=require('../utils/delivery-channel');
function harness(companies){
 const routes=[],writes=[],events=[],sent=[],generated=[];let connected=0,accounts=0;
 const router={post:(name,...handlers)=>routes.push({name,handlers}),get(){},delete(){}};
 const db={get:async(sql,args)=>sql.includes('FROM companies')?companies.find(c=>c.id===args[0]):sql.includes('FROM users')?{id:'u'}:sql.includes('cv_profiles')?{content:'CV'}:null,all:async()=>[],run:async(sql,args)=>{writes.push({sql,args});return {rowCount:1}}};
 const deps={express:{Router:()=>router},uuid:{v4:()=>`id-${writes.length}`},'../middleware/auth':{requireAuth(){}},'../middleware/async-handler':f=>f,'../utils/db':db,'../utils/ai':{generateEmail:async()=>{generated.push('email');return {subject:'Title',body:'Email'}},generateWhatsAppMessage:async()=>{generated.push('whatsapp');return 'WA'}},'../utils/gmail':{sendEmail:async()=>{sent.push('email');return {messageId:'m'}}},'../utils/gmail-accounts':{resolveAccount:async()=>{accounts++;return {gmail_account_id:'account',email:'sender@example.com'}}},'../utils/replyTracker':{},'../utils/whatsapp':{requireConnected:async()=>{connected++},sendWhatsAppMessage:async()=>{sent.push('whatsapp');return {messageId:'w'}}},'../utils/delivery-channel':channels};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../routes/email.js'),'utf8'),{require:id=>id.endsWith('access-control')?{checkToolAccess:async()=>{}}:deps[id],module:{exports:{}},process:{env:{}},console,Date,Set,Promise,setTimeout:f=>{f()}});
 return {writes,sent,generated,events,get connected(){return connected},get accounts(){return accounts},async post(name,body){let result,status=200;const res={status:s=>{status=s;return res},json:r=>{result=r},setHeader(){},flushHeaders(){},on(){},write:s=>{events.push(JSON.parse(s.slice(6)))},end(){}};await routes.find(r=>r.name===name).handlers.at(-1)({session:{userId:'u'},body},res);return {result,status}}};
}
const both={id:'both',name:'Both',email:'to@example.com',phone:'201012345678'};
test('company with both contacts uses explicitly selected WhatsApp, without Gmail',async()=>{const h=harness([both]);await h.post('/send',{companyId:'both',channel:'whatsapp',body:'Message'});assert.equal(h.sent.join(','),'whatsapp');assert.equal(h.accounts,0);assert.equal(h.connected,1);});
test('missing chosen contact is skipped and logged before AI or sender lookup',async()=>{const h=harness([{id:'phone',name:'Phone',phone:'201012345678'}]);const r=await h.post('/send',{companyId:'phone',channel:'email'});assert.equal(r.result.status,'skipped');assert.equal(h.sent.length,0);assert.equal(h.accounts,0);assert.equal(h.writes[0].args[5],'skipped');assert.equal(h.writes[0].args[7],'email');});
test('bulk email skips phone-only companies without auto-routing or failing them',async()=>{const h=harness([both,{id:'phone',name:'Phone',phone:'201012345678'}]);await h.post('/send-bulk',{companyIds:['phone','both'],channel:'email'});assert.equal(h.generated.join(','),'email');assert.equal(h.sent.join(','),'email');assert.equal(h.connected,0);const done=h.events.at(-1);assert.equal(done.sent,1);assert.equal(done.skipped,1);assert.equal(done.failed,0);assert.equal(h.events.find(e=>e.type==='skipped').companyId,'phone');});
test('scheduled WhatsApp pins log channel even when company has email',async()=>{const h=harness([both]);const r=await h.post('/send',{companyId:'both',channel:'whatsapp',body:'WA',scheduledAt:new Date(Date.now()+60000).toISOString()});assert.equal(r.result.status,'scheduled');assert.equal(h.accounts,0);const log=h.writes.find(w=>w.sql.includes('INSERT INTO email_log'));assert.equal(log.args[8],'whatsapp');assert.equal(log.args[4],both.phone);});
test('all ineligible scheduled recipients are skipped, not scheduled or connected',async()=>{const h=harness([{id:'email',name:'Email',email:'to@example.com'}]);const r=await h.post('/send-bulk',{companyIds:['email'],channel:'whatsapp',scheduleType:'scheduled',scheduledAt:new Date(Date.now()+60000).toISOString()});assert.equal(r.result.scheduled,0);assert.equal(r.result.skipped,1);assert.equal(h.connected,0);assert(!h.writes.some(w=>w.sql.includes('INSERT INTO scheduled_jobs')));});
test('invalid channel rejected and invalid contact does not silently switch channels',()=>{assert.throws(()=>channels.chooseChannel(both,'sms'));assert(channels.skipReason({email:'bad',phone:both.phone},'email'));assert(channels.skipReason({phone:'123'},'whatsapp'));});
test('scheduled execution preserves WhatsApp channel for a company with both contacts',async()=>{
 let tick,sent=[];const writes=[];
 const deps={'node-cron':{schedule:(pattern,fn)=>{if(pattern==='* * * * *')tick=fn;return {stop(){}}}},uuid:{v4:()=> 'log'},'./db':{all:async()=>[{id:'job',user_id:'u',company_id:'both',company_name:'Both',company_email:both.email,phone:both.phone,log_id:'saved'}],get:async sql=>sql.includes('FROM users')?{id:'u'}:sql.includes('cv_profiles')?{content:'CV'}:sql.includes('email_log')?{channel:'whatsapp',body:'saved message'}:null,run:async(sql,args)=>{writes.push({sql,args});return {rowCount:1}}},'./ai':{},'./gmail':{sendEmail:async()=>{throw new Error('wrong channel')}},'./gmail-accounts':{resolveAccount:async()=>{throw new Error('wrong sender')}},'./whatsapp':{sendWhatsAppMessage:async(u,phone,body)=>{sent.push({phone,body});return {messageId:'wa'}}},'./replyTracker':{},'../utils/delivery-channel':channels};
 const context={require:id=>id.endsWith('access-control')?{checkToolAccess:async()=>{}}:deps[id],module:{exports:{}},process:{env:{}},console,Date};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../utils/scheduler.js'),'utf8'),context);context.module.exports.startScheduler();await tick();assert.equal(sent.length,1);assert.equal(sent[0].phone,both.phone);assert.equal(sent[0].body,'saved message');
});
test('skip already sent is channel-specific even if company global status is sent',()=>{
 const source=fs.readFileSync(path.join(__dirname,'../public/assets/app.js'),'utf8');
 const start=source.indexOf('function companyChannelReason'),end=source.indexOf('async function previewChangeChannel');
 const elements={'send-channel':{value:'whatsapp'},'send-filter':{value:'all'},'opt-skip-sent':{checked:true},'channel-summary':{}};
 const context={document:{getElementById:id=>elements[id]},companies:[{...both,status:'sent'}],log:[{company_id:'both',channel:'email',status:'sent'}]};vm.runInNewContext(source.slice(start,end),context);
 assert.equal(context.deliveryQueue('whatsapp').length,1);assert.equal(context.deliveryQueue('email').length,0);
});
