const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function harness(staff=false,db={}){
 const before=[],routes=[];const router={use:fn=>before.push(fn)};for(const method of ['get','post','patch'])router[method]=(route,...handlers)=>routes.push({method:method.toUpperCase(),route,handlers});
 const dependencies={'express':{Router:()=>router},'crypto':require('crypto'),'../utils/db':db,'../middleware/auth':require('../middleware/auth'),'../middleware/async-handler':fn=>fn,'../utils/helpdesk':{isAdmin:async()=>staff,quota:()=>true}};
 const box={module:{exports:{}},require:id=>{if(!(id in dependencies))throw Error(id);return dependencies[id]},Set};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../routes/tickets.js'),'utf8'),box);
 return async(method,route,request={})=>{let status=200,body;const req={method,params:{id:'foreign'},query:{},body:{},session:{userId:'owner'},get:()=> '1',is:()=>true,...request};const res={set(){},status:n=>(status=n,res),json:x=>(body=x,res)};for(const fn of [...before,...routes.find(r=>r.route===route&&r.method===method).handlers]){let next=false;await fn(req,res,()=>next=true);if(!next)break;}return {status,body};};
}
test('helpdesk rejects unsigned visitors before DB access',async()=>{const call=harness();assert.equal((await call('GET','/',{session:null})).status,401);});
test('non-admin cannot inspect user list or errors',async()=>{const call=harness(false);assert.equal((await call('GET','/admin')).status,403);});
test('cross-site simple form posts rejected before writes',async()=>{const call=harness();assert.equal((await call('POST','/',{get:()=>undefined})).status,403);});
test('ticket detail binds owner and forbids foreign ticket',async()=>{let args;const call=harness(false,{get:async(sql,p)=>{args=p;return null;}});await assert.rejects(call('GET','/:id'),e=>e.status===404);assert.deepEqual(Array.from(args),['foreign','owner',false]);});
test('owner ticket list only selects own rows',async()=>{const call=harness(false,{all:async(sql,args)=>{assert.match(sql,/WHERE user_id=\$1/);assert.equal(args[0],'owner');return [];}});assert.equal((await call('GET','/')).body.tickets.length,0);});
test('invalid complaint cannot create a ticket',async()=>{let written=false;const call=harness(false,{run:()=>written=true});await assert.rejects(call('POST','/',{body:{subject:'x',body:'short',category:'general'}}));assert.equal(written,false);});
test('admin access defaults closed and exact email allowlist only',()=>{const env={ADMIN_EMAILS:' admin@example.com '};const box={module:{exports:{}},process:{env},require:id=>id==='crypto'?require('crypto'):{},Set,Map,Date};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../utils/helpdesk.js'),'utf8'),box);assert.equal(box.module.exports.adminEmail('ADMIN@example.com'),true);assert.equal(box.module.exports.adminEmail('eviladmin@example.com'),false);env.ADMIN_EMAILS='';assert.equal(box.module.exports.adminEmail('admin@example.com'),false);});
test('Gmail disabled error is actionable; unrelated errors retained',()=>{const {gmailError}=require('../utils/gmail-errors');assert.equal(gmailError(new Error('Gmail API has not been used in project 123 before or it is disabled.')).code,'GMAIL_API_DISABLED');const original=new Error('temporary');assert.equal(gmailError(original),original);});
test('split assets preserve original inline CSS/JS ordering',()=>{const html=fs.readFileSync(path.join(__dirname,'../public/index.html'),'utf8');assert(html.indexOf('assets/theme-init.js')<html.indexOf('assets/app.css'));assert(html.indexOf('assets/app.js')<html.indexOf('assets/workspace.js'));assert(html.indexOf('assets/workspace.js')<html.indexOf('assets/tickets.js'));assert(!/<style[\s>]/.test(html));assert(!/<script>/.test(html));});
