'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..');
function load(file,deps={},extras={}){const box={module:{exports:{}},require:id=>Object.hasOwn(deps,id)?deps[id]:require(id),process:{env:{SESSION_SECRET:'test-only-secret'}},console,Date,Buffer,URL,URLSearchParams,AbortSignal,...extras};vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),box);return box.module.exports;}
test('health cache skips unavailable models and separates replacement keys',()=>{const h=load('utils/ai-health.js');h.failed('openrouter','old','slow','TIMEOUT');assert(h.available('openrouter','old','slow'));assert.equal(h.available('openrouter','new','slow'),null);assert.equal(h.available('openrouter','old','fast'),null);h.success('openrouter','old','slow');assert.equal(h.available('openrouter','old','slow'),null);h.failed('openrouter','old','slow','QUOTA');assert(h.available('openrouter','old','fast'));});
test('Supabase identity is verified remotely; unconfirmed email cannot sign in',async()=>{let fetched;const api=load('utils/supabase-auth.js',{'./db':{}},{process:{env:{SUPABASE_URL:'https://project.supabase.co',SUPABASE_PUBLISHABLE_KEY:'publishable'}},fetch:async(url,opts)=>{fetched={url,opts};return {ok:true,json:async()=>({id:'verified-id',email:'user@example.com'})};}});await assert.rejects(api.identity('forged-token'),e=>e.status===403);assert.equal(fetched.url,'https://project.supabase.co/auth/v1/user');assert.equal(fetched.opts.headers.Authorization,'Bearer forged-token');});
test('Supabase never silently takes over a legacy Google account by matching email',async()=>{let inserted=false;const api=load('utils/supabase-auth.js',{'./db':{get:async sql=>sql.includes('WHERE supabase_id')?null:sql.includes('lower(email)')?{id:'google-owner'}:(inserted=true,{id:'new'})}});await assert.rejects(api.localUser({id:'sb',email:'existing@example.com'}),e=>e.status===409);assert.equal(inserted,false);});
test('preview loads a saved draft and never generates on open',()=>{const source=fs.readFileSync(path.join(root,'public/assets/app.js'),'utf8'),preview=source.slice(source.indexOf('async function previewOne'),source.indexOf('let previewBatchActive'));assert(preview.includes('/api/writing/draft?'));assert(!preview.includes('await genPreview'));assert(source.includes("addEventListener('input',()=>previewEdited())"));});
test('notifications use top layer and explicit gesture-based sound unlocking',()=>{const source=fs.readFileSync(path.join(root,'public/assets/notifications.js'),'utf8');assert(source.includes("setAttribute('popover','manual')"));assert(source.includes('popup.showPopover()'));assert(source.includes('await unlockSound();await sound();'));assert(!source.includes('!state.settings.toast||dialog.open'));assert(!source.includes('مؤشر تحميل صور؛'));});
test('actual PostgreSQL migrations, CV versions, draft ownership, quotas and delivery idempotency',async()=>{
 const {PGlite}=require('@electric-sql/pglite');const pg=new PGlite();const db={query:(s,p)=>pg.query(s,p),run:async(s,p)=>p===undefined?(await pg.exec(s),{rowCount:1}):pg.query(s,p),get:async(s,p)=>(await pg.query(s,p)).rows[0],all:async(s,p)=>(await pg.query(s,p)).rows,pool:{connect:async()=>({query:(s,p)=>p===undefined?pg.query(s):pg.query(s,p),release(){}})}};
 try{
 const src=fs.readFileSync(path.join(root,'utils/db.js'),'utf8');const schema=src.match(/await query\(`([\s\S]*?)`\);/)[1];await pg.exec(schema);await pg.exec('ALTER TABLE email_log ADD COLUMN sender_account_id TEXT;ALTER TABLE email_log ADD COLUMN sender_email TEXT;');
 const migration=load('utils/launch-schema.js',{'./db':db});await migration.ensureLaunchSchema();await migration.ensureLaunchSchema();await pg.exec("INSERT INTO users(id,email) VALUES('owner','a@test.com'),('other','b@test.com');INSERT INTO companies(id,user_id,name,email) VALUES('co','owner','Company','recipient@test.com');");
 const cv=load('utils/cv-store.js',{'./db':db});const first=await cv.save('owner',{content:'old CV',filename:'first.pdf',pdf_data:Buffer.from('%PDF-original')});const second=await cv.save('owner',{content:'edited CV',filename:'manual'},true);assert.equal((await db.get('SELECT COUNT(*) AS n FROM cv_profiles')).n,2);assert.equal((await cv.active('owner')).id,second);assert.equal(Buffer.from((await cv.active('owner')).pdf_data).toString(),'%PDF-original');assert.equal(await cv.active('other',first),undefined);
 const drafts=load('utils/drafts.js',{'./db':db});await drafts.save('owner','co','email','Subject','Approved draft');assert.equal((await drafts.load('owner','co','email')).body,'Approved draft');await assert.rejects(drafts.save('other','co','email','Title','foreign'),e=>e.status===404);
 const quota=load('utils/usage-limits.js',{'./db':db,'./plan-catalog':require('../utils/plan-catalog')});await db.run('UPDATE users SET ai_limit=1 WHERE id=$1',['owner']);await quota.consume('owner','ai');await assert.rejects(quota.consume('owner','ai'),e=>e.status===429);
 let sends=0;const delivery=load('utils/delivery.js',{'./db':db,'./delivery-channel':require('../utils/delivery-channel'),'./access-control':{checkToolAccess:async()=>{}},'./usage-limits':quota,'./gmail-accounts':{resolveAccount:async()=>({gmail_account_id:null,email:'sender@test.com'})},'./cv-store':cv,'./gmail':{sendEmail:async()=>{sends++;return {messageId:'provider-message',threadId:'thread'};}}});
 const params={companyId:'co',channel:'email',subject:'Subject',body:'Edited draft',idempotencyKey:'unique-request-123'};const one=await delivery.deliver('owner',params),two=await delivery.deliver('owner',params);assert.equal(one.status,'sent');assert.equal(two.messageId,'provider-message');assert.equal(sends,1);await assert.rejects(delivery.deliver('owner',{...params,body:'changed'}),e=>e.status===409);assert.equal((await db.get('SELECT COUNT(*) AS n FROM email_log')).n,1);
 const failing=load('utils/delivery.js',{'./db':db,'./delivery-channel':require('../utils/delivery-channel'),'./access-control':{checkToolAccess:async()=>{}},'./usage-limits':quota,'./gmail-accounts':{resolveAccount:async()=>({email:'sender@test.com'})},'./cv-store':cv,'./gmail':{sendEmail:async()=>{sends++;throw new Error('lost acknowledgement');}}});const failure=await failing.deliver('owner',{...params,idempotencyKey:'uncertain-123'});assert.equal(failure.status,'uncertain');await failing.deliver('owner',{...params,idempotencyKey:'uncertain-123'});assert.equal(sends,2);
 const before=(await db.get("SELECT amount FROM usage_daily WHERE user_id='owner' AND kind='send'")).amount;
 const rejected=load('utils/delivery.js',{'./db':db,'./delivery-channel':require('../utils/delivery-channel'),'./access-control':{checkToolAccess:async()=>{}},'./usage-limits':quota,'./gmail-accounts':{resolveAccount:async()=>{throw Error('account disconnected');}},'./cv-store':cv});
 assert.equal((await rejected.deliver('owner',{...params,idempotencyKey:'failed-account-123'})).status,'failed');assert.equal((await db.get("SELECT amount FROM usage_daily WHERE user_id='owner' AND kind='send'")).amount,before);
 await db.run("UPDATE companies SET email=NULL WHERE id='co'");assert.equal((await rejected.deliver('owner',{...params,idempotencyKey:'skip-account-123'})).status,'skipped');assert.equal((await db.get("SELECT amount FROM usage_daily WHERE user_id='owner' AND kind='send'")).amount,before);
 }finally{await pg.close();}
});
test('reviewed campaigns are owner-scoped and cannot start while any draft is unapproved',async()=>{
 const {PGlite}=require('@electric-sql/pglite');const pg=new PGlite(),db={get:async(s,p)=>(await pg.query(s,p)).rows[0],all:async(s,p)=>(await pg.query(s,p)).rows,run:async(s,p)=>p===undefined?(await pg.exec(s),{rowCount:1}):pg.query(s,p),pool:{connect:async()=>({query:(s,p)=>pg.query(s,p),release(){}})}};
 try{const base=fs.readFileSync(path.join(root,'utils/db.js'),'utf8').match(/await query\(`([\s\S]*?)`\);/)[1];await pg.exec(base);await load('utils/launch-schema.js',{'./db':db}).ensureLaunchSchema();await pg.exec("INSERT INTO users(id,email) VALUES('owner','a@test.com'),('other','b@test.com');INSERT INTO companies(id,user_id,name,phone) VALUES('co','owner','Company','201000000000'),('missing','owner','Missing',NULL);INSERT INTO cv_profiles(id,user_id,content) VALUES('cv','owner','CV');");
 const routes=[];const router={use(){}};for(const method of ['get','post','patch'])router[method]=(route,...handlers)=>routes.push({method,route,handler:handlers.at(-1)});
 load('routes/campaigns.js',{express:{Router:()=>router},'../utils/db':db,'../middleware/async-handler':f=>f,'../middleware/auth':{requireAuth(){}},'../utils/cv-store':{active:async()=>({id:'cv',content:'CV'})},'../utils/delivery-channel':require('../utils/delivery-channel'),'../utils/access-control':{checkToolAccess:async()=>{}}});
 async function invoke(method,path,owner,params={},body={}){let status=200,data;const res={status:n=>(status=n,res),json:x=>(data=x,res)};await routes.find(r=>r.method===method&&r.route===path).handler({session:{userId:owner},params,body},res);return {status,data};}
 const created=await invoke('post','/','owner',{}, {companyIds:['co','missing'],channel:'whatsapp'});const id=created.data.id;assert(id);const detail=await invoke('get','/:id','owner',{id});assert.equal(detail.data.items.length,2);assert.equal(detail.data.items.find(x=>x.company_id==='missing').status,'skipped');assert.equal((await invoke('get','/:id','other',{id})).status,404);
 assert.equal((await invoke('post','/:id/:action','owner',{id,action:'start'})).status,409);
 const item=detail.data.items.find(x=>x.company_id==='co');await invoke('patch','/:id/items/:item','owner',{id,item:item.id},{subject:'',body:'Manually reviewed message'});assert.equal((await invoke('post','/:id/:action','owner',{id,action:'start'})).status,200);assert.equal((await db.get('SELECT status FROM campaigns WHERE id=$1',[id])).status,'running');assert.equal((await invoke('patch','/:id/items/:item','owner',{id,item:item.id},{subject:'',body:'late change'})).status,409);
 await invoke('post','/:id/:action','owner',{id,action:'pause'});assert.equal((await db.get('SELECT status FROM campaigns WHERE id=$1',[id])).status,'paused');await invoke('post','/:id/:action','owner',{id,action:'resume'});await invoke('post','/:id/:action','owner',{id,action:'cancel'});assert.equal((await db.get('SELECT status FROM campaign_items WHERE id=$1',[item.id])).status,'cancelled');
 }finally{await pg.close();}
});

test('notification chime resumes suspended audio and schedules two audible tones',async()=>{
 const vm=require('node:vm'),source=fs.readFileSync(path.join(root,'public/assets/notifications.js'),'utf8');
 const fragment=source.slice(source.indexOf(' let audio;'),source.indexOf(" for(const event"));
 const nodes=[];
 class Audio{constructor(){this.state='suspended';this.currentTime=10;this.destination={};}async resume(){this.state='running';}createGain(){const n={gain:{value:0,setValueAtTime(){},linearRampToValueAtTime(value,time){n.attack={value,time};},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}};nodes.push(n);return n;}createOscillator(){const n={frequency:{},connect(){},disconnect(){},start(time){n.startTime=time;},stop(time){n.stopTime=time;}};nodes.push(n);return n;}}
 const context={window:{AudioContext:Audio},tr:(a,b)=>b,setTimeout:()=>{}};vm.createContext(context);
 await vm.runInContext(fragment+'; (async()=>{await unlockSound();await sound();})()',context);
 const tones=nodes.filter(n=>n.frequency);assert.equal(tones.length,2);assert.equal(nodes[0].gain.value,.28);assert.equal(tones[0].frequency.value,784);assert.equal(tones[1].frequency.value,1046);assert(tones[1].startTime>tones[0].startTime);assert(tones.every(n=>n.stopTime>n.startTime));
});
