'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.join(__dirname,'..');
function load(file,deps,extra={}){const box={module:{exports:{}},require:key=>deps[key]??require(key),Buffer,URL,console,process:{env:{}},setInterval:()=>({unref(){}}),clearInterval(){},...extra};vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),box);return box.module.exports;}
function helper(){return load('utils/notifications.js',{'./db':{},'./connection-secrets':{},'./helpdesk':{adminEmail:()=>false}});}
test('notification defaults are explicit, sound and browser off',()=>{const n=helper();assert.equal(n.preferences().sound,false);assert.equal(n.preferences().browser,false);assert.equal(n.preferences({types:{email_open:false}}).types.email_reply,true);assert.equal(n.preferences({types:{email_open:false}}).types.email_open,false);});
test('notification settings reject unknown kinds, strings and untrusted languages',()=>{const n=helper();for(const data of [{sound:'yes'},{types:{send_everything:true}},{types:{wa_reply:1}},{language:'xx'}])assert.throws(()=>n.validatePreferences(data),e=>e.status===400);});
test('push subscriptions reject arbitrary/internal endpoints and invalid curve points',()=>{const n=helper(),curve=crypto.createECDH('prime256v1');curve.generateKeys();const s={endpoint:'https://fcm.googleapis.com/fcm/send/token',keys:{p256dh:curve.getPublicKey().toString('base64url'),auth:crypto.randomBytes(16).toString('base64url')}};assert.equal(n.validSubscription(s),true);for(const endpoint of ['http://fcm.googleapis.com/test','https://127.0.0.1/test','https://web.push.apple.com.evil.test/test','https://user:pass@fcm.googleapis.com/test','https://fcm.googleapis.com:8000/test'])assert.equal(n.validSubscription({...s,endpoint}),false);assert.equal(n.validSubscription({...s,keys:{...s.keys,p256dh:Buffer.alloc(65,4).toString('base64url')}}),false);});
function harness(staff=false,db={}){const before=[],routes=[];const router={use:fn=>before.push(fn)};for(const method of ['get','post','patch'])router[method]=(route,...handlers)=>routes.push({method:method.toUpperCase(),route,handlers});const n=helper();load('routes/notifications.js',{'express':{Router:()=>router},'../utils/db':db,'../middleware/auth':require('../middleware/auth'),'../middleware/async-handler':fn=>fn,'../utils/helpdesk':{isAdmin:async()=>staff,quota:()=>true},'../utils/notifications':{...n,ensureRelease:async()=>{}},'../utils/connection-secrets':{seal:x=>JSON.stringify(x)}});return async(method,route,request={})=>{let status=200,body;const req={method,params:{},query:{},body:{},session:{userId:'owner'},get:()=> '1',is:()=>true,...request};const res={set(){},status:n=>(status=n,res),json:x=>(body=x,res)};for(const fn of [...before,...routes.find(r=>r.route===route&&r.method===method).handlers]){let next=false;await fn(req,res,()=>next=true);if(!next)break;}return {status,body};};}
test('notifications reject unauthenticated and cross-site writes',async()=>{const h=harness();assert.equal((await h('GET','/',{session:null})).status,401);assert.equal((await h('PATCH','/settings',{get:()=>undefined})).status,403);});
test('reading someone else notification is always bound to session owner',async()=>{let args;const h=harness(false,{run:async(s,p)=>{args=p;assert.match(s,/user_id=\$2/);}});await h('PATCH','/read',{body:{id:'9123'}});assert.equal(args[1],'owner');});
test('mark all uses observed timestamp so a newer grouped event stays unread',async()=>{let args;const h=harness(false,{run:async(s,p)=>{assert.match(s,/updated_at<=\$2/);args=p;}});await h('PATCH','/read',{body:{all:true,before:'2026-10-08T10:00:00Z'}});assert.equal(args[1],'2026-10-08T10:00:00Z');await assert.rejects(h('PATCH','/read',{body:{all:true,before:'bad'}}),e=>e.status===400);});
test('non-admin cannot broadcast releases or read release control',async()=>{const h=harness();await assert.rejects(h('POST','/releases'),e=>e.status===403);await assert.rejects(h('GET','/releases'),e=>e.status===403);});
test('push worker exposes only generic text and same-origin destination',()=>{const worker=fs.readFileSync(path.join(root,'public/notifications-sw.js'),'utf8');assert(worker.includes("new URL('/app?notifications=1',self.location.origin)"));assert(!worker.includes("addEventListener('fetch'"));const src=fs.readFileSync(path.join(root,'utils/notifications.js'),'utf8');const payload=src.slice(src.indexOf('const payload='),src.indexOf('for(const sub of subs)'));assert(!/company|reply_text|ticket/.test(payload));assert(src.includes('pg_try_advisory_lock'));assert(src.includes('revision=$2'));});
test('actual Postgres triggers deduplicate, group, respect preferences and roll back',async()=>{
 const {PGlite}=require('@electric-sql/pglite');const db=new PGlite();
 try{
 await db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,email TEXT); CREATE TABLE email_log(id TEXT PRIMARY KEY,user_id TEXT,company_name TEXT,channel TEXT,status TEXT,open_count INTEGER DEFAULT 0,replied INTEGER DEFAULT 0,reply_text TEXT,reply_message_id TEXT,whatsapp_delivered_at BIGINT,whatsapp_read_at BIGINT,whatsapp_reply_at BIGINT,whatsapp_reply_message_id TEXT); CREATE TABLE support_tickets(id TEXT PRIMARY KEY,user_id TEXT,subject TEXT,status TEXT,updated_at TIMESTAMPTZ DEFAULT NOW()); CREATE TABLE support_messages(id TEXT PRIMARY KEY,ticket_id TEXT,user_id TEXT,staff BOOLEAN); CREATE TABLE scheduled_jobs(id TEXT PRIMARY KEY,user_id TEXT,status TEXT,log_id TEXT,company_id TEXT); CREATE TABLE support_events(id TEXT PRIMARY KEY,user_id TEXT,area TEXT,status INTEGER,created_at TIMESTAMPTZ DEFAULT NOW());`);
 await db.exec(fs.readFileSync(path.join(root,'utils/notifications-schema.sql'),'utf8'));
 await db.exec("INSERT INTO users VALUES('u','user@example.test'),('v','other@example.test'),('a','admin@example.test'); INSERT INTO notification_staff VALUES('a'); INSERT INTO email_log(id,user_id,company_name,channel,status) VALUES('e','u','Company','email','sent'),('e2','u','Company2','email','sent'),('wa','u','WA','whatsapp','sent');");
 const rows=async()=> (await db.query('SELECT * FROM notifications ORDER BY id')).rows;
 assert.equal((await rows()).length,0);
 await db.exec("UPDATE email_log SET open_count=1 WHERE id='e'; UPDATE email_log SET open_count=2 WHERE id='e'; UPDATE email_log SET open_count=1 WHERE id='e2';");let r=await rows();assert.equal(r.length,1);assert.equal(r[0].event_count,2);assert.equal(r[0].kind,'email_open');
 await db.exec("UPDATE notifications SET read_at=NOW(); UPDATE email_log SET replied=1,reply_message_id='r1',reply_text='Hello' WHERE id='e'; UPDATE email_log SET replied=1,reply_message_id='r1' WHERE id='e'; UPDATE email_log SET reply_message_id='r2' WHERE id='e';");r=await rows();assert.equal(r.filter(x=>x.kind==='email_reply').length,2);
 await db.exec("UPDATE email_log SET whatsapp_delivered_at=1,whatsapp_read_at=2 WHERE id='wa'; UPDATE email_log SET whatsapp_read_at=2 WHERE id='wa'; UPDATE email_log SET replied=1,whatsapp_reply_at=3,reply_text='Hi' WHERE id='wa';");r=await rows();assert.equal(r.filter(x=>x.kind==='wa_delivered').length,1);assert.equal(r.filter(x=>x.kind==='wa_read').length,1);assert.equal(r.filter(x=>x.kind==='wa_reply').length,1);
 await db.exec("UPDATE email_log SET whatsapp_reply_message_id='wa-second',whatsapp_reply_at=3,reply_text='Another reply in the same second' WHERE id='wa'; UPDATE email_log SET whatsapp_reply_message_id='wa-second' WHERE id='wa';");assert.equal((await rows()).filter(x=>x.kind==='wa_reply').length,2);
 await db.exec(`INSERT INTO notification_preferences VALUES('u','{"types":{"send_failed":false},"browser":true}'); UPDATE email_log SET status='failed' WHERE id='e2'; UPDATE email_log SET reply_message_id='r3' WHERE id='e';`);r=await rows();assert.equal(r.filter(x=>x.kind==='send_failed').length,0);assert.equal((await db.query('SELECT * FROM notification_push_jobs')).rows.length,1);
 await db.exec("INSERT INTO support_tickets(id,user_id,subject,status) VALUES('t','u','Problem','open'); INSERT INTO support_messages VALUES('m','t','a',true); UPDATE support_tickets SET status='waiting_user',updated_at=NOW() WHERE id='t'; INSERT INTO support_messages VALUES('m2','t','u',false);");r=await rows();assert.equal(r.find(x=>x.kind==='admin_ticket').user_id,'a');assert.equal(r.find(x=>x.kind==='ticket_reply').user_id,'u');assert.equal(r.find(x=>x.kind==='admin_ticket_reply').user_id,'a');assert.equal(r.find(x=>x.kind==='ticket_status').data.status,'waiting_user');
 const before=r.length;await db.exec("BEGIN; INSERT INTO email_log(id,user_id,channel,status) VALUES('rollback','v','email','failed'); ROLLBACK;");assert.equal((await rows()).length,before);
 await db.exec("INSERT INTO support_events VALUES('x1','u','providers',500,NOW()),('x2','u','providers',500,NOW()),('x3','u','providers',500,NOW());");r=await rows();assert.equal(r.filter(x=>x.kind==='admin_errors').length,1);assert.equal(r.filter(x=>x.kind==='connection_issue').length,1);
 await db.exec("INSERT INTO scheduled_jobs VALUES('j','u','pending','e','c'); UPDATE scheduled_jobs SET status='processing' WHERE id='j'; UPDATE scheduled_jobs SET status='sent' WHERE id='j';");r=await rows();assert.equal(r.filter(x=>x.kind==='schedule_started').length,1);assert.equal(r.filter(x=>x.kind==='schedule_done').length,1);
 await db.exec("SELECT mrsaal_notify('u','release:version','release','updates','{}','{}'); SELECT mrsaal_notify('u','release:version','release','updates','{}','{}');");assert.equal((await rows()).filter(x=>x.kind==='release').length,1);
 const call=harness(false,{get:async(s,p)=>(await db.query(s,p)).rows[0],all:async(s,p)=>(await db.query(s,p)).rows,run:async(s,p)=>db.query(s,p)});
 await db.exec("UPDATE notifications SET updated_at='2026-10-08T10:00:00.123456Z',read_at=NULL WHERE kind='release'");
 const page=await call('GET','/',{session:{userId:'u'},query:{since:'2026-01-01T00:00:00Z'}});assert.equal(page.status,200);assert(page.body.items.every(n=>n.category!=='admin'));const release=page.body.items.find(n=>n.kind==='release');assert.equal(release.revision,'2026-10-08T10:00:00.123456Z');
 await call('PATCH','/read',{session:{userId:'u'},body:{id:String(release.id),revision:release.revision}});assert((await rows()).find(n=>n.id===release.id).read_at,'microsecond precision must not prevent marking a notification read');
 
 }finally{await db.close();}
});
test('push outbox removes expired devices and retries transient errors with revision guard',async()=>{
 const writes=[],curve=crypto.createECDH('prime256v1');curve.generateKeys();const creds={publicKey:curve.getPublicKey().toString('base64url'),privateKey:curve.getPrivateKey().toString('base64url')};let deliveries=0;
 const job={notification_id:'7',user_id:'u',kind:'email_reply',revision:'2026-10-08T10:00:00.123456Z',attempts:0,settings:{browser:true,language:'en'}};
 const api=load('utils/notifications.js',{'./db':{pool:{connect:async()=>({query:async s=>({rows:[{locked:true}]}),release(){}})},run:async(sql,params)=>{writes.push({sql,params});},get:async()=>({credentials:JSON.stringify(creds)}),all:async(sql)=>sql.includes('SELECT id,email')?[]:sql.includes('SELECT j.*')?[job]:sql.includes('SELECT endpoint_hash')?[{endpoint_hash:'gone',subscription:JSON.stringify({endpoint:'https://fcm.googleapis.com/gone'})},{endpoint_hash:'retry',subscription:JSON.stringify({endpoint:'https://fcm.googleapis.com/retry'})}]:[]},'./connection-secrets':{seal:JSON.stringify,unseal:JSON.parse},'./helpdesk':{adminEmail:()=>false},'web-push':{setVapidDetails(){},sendNotification:async(sub,payload)=>{deliveries++;const data=JSON.parse(payload);assert.equal(data.title,'Mrsaal · New notifications');assert.equal(data.url,'/app?notifications=1');assert(!JSON.stringify(data).includes('company'));throw {statusCode:sub.endpoint.endsWith('gone')?410:503};}}});
 await api.dispatchPush();assert.equal(deliveries,2);assert(writes.some(w=>w.sql.startsWith('DELETE FROM notification_push_subscriptions')&&w.params[0]==='gone'));assert(writes.some(w=>w.sql.includes('attempts=attempts+1')&&w.params[1]===job.revision));assert(!writes.some(w=>w.sql.startsWith('DELETE FROM notification_push_jobs')));
});
test('real web-push library encrypts a notification with persisted native ECDH VAPID keys',()=>{
 const webpush=require('web-push'),app=crypto.createECDH('prime256v1'),browser=crypto.createECDH('prime256v1');app.generateKeys();browser.generateKeys();
 webpush.setVapidDetails('https://mrsaal.ebnhussein.co',app.getPublicKey().toString('base64url'),app.getPrivateKey().toString('base64url'));
 const sub={endpoint:'https://fcm.googleapis.com/fcm/send/local-test-only',keys:{p256dh:browser.getPublicKey().toString('base64url'),auth:crypto.randomBytes(16).toString('base64url')}};
 const details=webpush.generateRequestDetails(sub,JSON.stringify({title:'Mrsaal',url:'/app?notifications=1'}),{TTL:3600,topic:'mrsaal-notifications'});
 assert.equal(details.headers['Content-Encoding'],'aes128gcm');assert.match(details.headers.Authorization,/^vapid /);assert(details.body.length>40);assert(!details.body.toString().includes('notifications=1'));
});
