 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..');
function load(file,deps){const box={module:{exports:{}},require:id=>deps[id]||require(id),process:{env:{AI_SECOND_PASS:'true'}},console,Date};vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),box);return box.module.exports;}
function engine({source='mrsaal',fallback=false,failed=false,invalid=false}={}){
 const calls=[],records=[],usage={reserve:async(u,k)=>(records.push(['reserve',k]),k),commit:async(u,k)=>records.push(['commit',k]),release:async(u,k)=>records.push(['release',k])};
 const reviewed={subject:'Hello',body:'A short honest application.',notes:[],needsUserInput:invalid};
 const ai=load('utils/ai.js',{'./writing-profile':require('../utils/writing-profile'),'./db':{get:async()=>({ai_source:source,ai_personal_fallback:fallback})},'./ai-leases':{acquire:async()=>1,release:async()=>{}},'./usage-limits':usage,'./ai-legacy':{callGemini:async(p,t,key,model,valid)=>{calls.push(['mrsaal',key,model]);if(failed)throw Error('offline');const text=JSON.stringify(reviewed);assert(valid(text));return text;}},'./ai-providers':{callUserAI:async()=>{calls.push(['personal']);return JSON.stringify(reviewed);}}});
 return {ai,calls,records};
}
const args={userId:'owner',apiKey:'never-auto-spend-this-key',modelName:'personal-model',cv:'Developer',company:{name:'Example'},instructions:''};
test('Mrsaal is default, personal secrets never passed; two review calls use one successful draft credit',async()=>{const e=engine();await e.ai.generateEmail(args);assert.equal(e.calls.length,2);assert.deepEqual(e.calls[0],['mrsaal',null,null]);assert.deepEqual(e.records,[['reserve','ai'],['commit','ai']]);});
test('failed or insufficient draft refunds credit and never silently uses personal keys',async()=>{for(const options of [{failed:true},{invalid:true}]){const e=engine(options);await assert.rejects(e.ai.generateEmail(args));assert(e.calls.every(c=>c[0]==='mrsaal'));assert.deepEqual(e.records,[['reserve','ai'],['release','ai']]);}});
test('personal source keeps price independent and uses separate safety counter',async()=>{const e=engine({source:'personal'});await e.ai.generateEmail(args);assert(e.calls.every(c=>c[0]==='personal'));assert.deepEqual(e.records,[['reserve','personal_ai'],['commit','personal_ai']]);});
test('only explicit fallback consent permits personal provider; returns included draft reservation',async()=>{const e=engine({failed:true,fallback:true});await e.ai.generateEmail(args);assert.deepEqual(e.records,[['reserve','ai'],['release','ai'],['reserve','personal_ai'],['commit','personal_ai']]);assert.equal(e.calls.filter(c=>c[0]==='mrsaal').length,1);});
test('assistant and style requests have independent counters',async()=>{const e=engine();await e.ai.callGemini('help',50,null,null,()=>true,'owner',null,'assistant');assert.deepEqual(e.records,[['reserve','assistant'],['commit','assistant']]);});
test('real PostgreSQL reservation caps, refunds, ownership, rollover and monthly plan balance',async()=>{
 const {PGlite}=require('@electric-sql/pglite'),pg=new PGlite();const db={get:async(s,p)=>(await pg.query(s,p)).rows[0],run:async(s,p)=>p?pg.query(s,p):pg.exec(s),pool:{query:(s,p)=>pg.query(s,p),connect:async()=>({query:(s,p)=>pg.query(s,p),release(){}})}};
 try{const schema=fs.readFileSync(path.join(root,'utils/db.js'),'utf8').match(/await query\(`([\s\S]*?)`\);/)[1];await pg.exec(schema);await load('utils/launch-schema.js',{'./db':db}).ensureLaunchSchema();await pg.exec("INSERT INTO users(id,email,plan_id,ai_limit) VALUES('owner','owner@test.com','start',100),('other','other@test.com','beta',100)");
 const u=load('utils/usage-limits.js',{'./db':db,'./plan-catalog':require('../utils/plan-catalog')});
 const refunded=await u.reserve('owner','ai');await u.release('other',refunded);assert.equal((await u.summary('owner')).credits.find(c=>c.kind==='ai').used,1);await u.release('owner',refunded);await u.release('owner',refunded);assert.equal((await db.get("SELECT amount FROM usage_daily WHERE user_id='owner' AND kind='ai'")).amount,0);
 for(let i=0;i<10;i++){const id=await u.reserve('owner','ai');await u.commit('owner',id);}await assert.rejects(u.reserve('owner','ai'),e=>e.status===429);assert.equal((await u.summary('owner')).credits.find(c=>c.kind==='ai').remaining,0);
 const personal=await u.reserve('owner','personal_ai');await u.commit('owner',personal);assert.equal((await u.summary('owner')).credits.find(c=>c.kind==='ai').used,10);
 const shifted=await u.reserve('other','ai');await pg.query("UPDATE usage_reservations SET day=CURRENT_DATE-1 WHERE id=$1",[shifted]);await pg.exec("INSERT INTO usage_daily(user_id,kind,day,amount) VALUES('other','ai',CURRENT_DATE-1,1)");await u.release('other',shifted);assert.equal((await db.get("SELECT amount FROM usage_daily WHERE user_id='other' AND kind='ai' AND day=CURRENT_DATE")).amount,1);
 }finally{await pg.close();}
});
test('public plans clearly remain proposed and bilingual; mobile core home has native collapsible details',()=>{const ui=require('../utils/public-minimal');for(const lang of ['ar','en']){const html=ui.plansContent(lang);assert(html.includes('149'));assert(html.includes('249'));assert(html.includes('/'+lang+'/signup'));assert(!html.includes('checkout'));assert(html.includes('<details>'));const home=ui.mobileHome(lang);assert(home.includes('how-it-works-mobile'));assert(home.includes('/'+lang+'/product'));assert(home.includes('<details>'));}assert.equal(require('../utils/plan-catalog').billingEnabled,false);});
