'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..');
async function ui(search='',responses={},pathname='',options={}){
 const nodes={};for(const [,id]of fs.readFileSync(path.join(root,'public/account.html'),'utf8').matchAll(/\bid="([^"]+)"/g))nodes[id]={id,hidden:false,disabled:false,required:false,value:'',checked:false,textContent:'',focus(){this.focused=true;}};
 const calls=[],redirects=[],window={};const widgets=[];if(options.captcha){window.turnstile={render(host,config){widgets.push({host:host.id,config});return widgets.length;},remove(){},reset(){}};}if(options.width)for(const node of Object.values(nodes))node.getBoundingClientRect=()=>({width:options.width});let interval;const context={turnstile:window.turnstile,document:{body:{dataset:{theme:options.theme||'light'}},documentElement:{},getElementById:id=>nodes[id],head:{append(){}},createElement:()=>({})},window,location:{search,pathname,replace:url=>redirects.push(url)},URLSearchParams,Date,Set,AbortController,setTimeout,clearTimeout,setInterval:fn=>{interval=fn;},fetch:async(url,options)=>{calls.push({url,body:options?.body&&JSON.parse(options.body)});let data=responses[url]??(url==='/auth/email-config'?{enabled:true}:{});if(typeof data==='function')data=await data();return {ok:true,status:200,json:async()=>data};}};
 vm.runInNewContext(fs.readFileSync(path.join(root,'public/assets/account.js'),'utf8'),context);await new Promise(setImmediate);
 return {nodes,calls,redirects,interval,widgets};
}
test('signup requires profile and consent; signin hides and disables those fields',async()=>{const x=await ui('?mode=signup');for(const id of ['name','phone','terms','confirm-password'])assert.equal(x.nodes['account-'+id].required,true);x.nodes['account-signin'].onclick();for(const id of ['name','phone','terms','confirm-password'])assert.equal(x.nodes['account-'+id].disabled,true);assert.equal(x.nodes['account-password'].required,true);});
test('signup waits for verification, clears passwords and blocks immediate resend',async()=>{const x=await ui('?mode=signup',{'/auth/email/signup':{requiresConfirmation:true,email:'new@example.com',retryAfter:60}});Object.assign(x.nodes['account-email'],{value:'new@example.com'});x.nodes['account-password'].value=x.nodes['account-confirm-password'].value='safe_password_123';x.nodes['account-name'].value='Ahmed';x.nodes['account-phone'].value='+201012345678';x.nodes['account-terms'].checked=true;await x.nodes['account-form'].onsubmit({preventDefault(){}});assert.equal(x.nodes['account-form'].hidden,true);assert.equal(x.nodes['account-waiting'].hidden,false);assert.equal(x.nodes['account-resend'].disabled,true);assert.equal(x.nodes['account-password'].value,'');assert.deepEqual(x.redirects,[]);assert.equal(x.calls.find(c=>c.url.endsWith('/signup')).body.acceptTerms,true);x.nodes['account-confirmed-login'].onclick();assert.equal(x.nodes['account-waiting'].hidden,true);assert.equal(x.nodes['account-email'].value,'new@example.com');});
test('confirmation landing makes no verification request until explicit click',async()=>{const x=await ui('?mode=confirm',{'/auth/email/confirm':{redirect:'/auth/account?confirmed=1'}});assert.equal(x.calls.some(c=>c.url.endsWith('/confirm')),false);await x.nodes['account-form'].onsubmit({preventDefault(){}});assert.deepEqual(x.redirects,['/auth/account?confirmed=1']);});
test('Google profile completion prefills current user and preserves English layout',async()=>{const x=await ui('?mode=profile&lang=en',{'/auth/email/profile':{name:'Ahmed',contact_phone:'+201012345678'}});assert.equal(x.nodes['account-name'].value,'Ahmed');assert.equal(x.nodes['account-phone'].value,'+201012345678');assert.equal(x.nodes['account-google'].hidden,true);assert.equal(x.nodes['account-password'].disabled,true);assert.equal(x.nodes['account-privacy'].href,'/en/privacy');});

test('public signup opens registration directly with English copy and profile fields',async()=>{const x=await ui('',{},'/en/signup');assert.equal(x.nodes['account-title'].textContent,'Create your account');assert.equal(x.nodes['account-name'].required,true);assert.equal(x.nodes['account-phone'].required,true);assert.equal(x.nodes['account-signup'].hidden,true);assert.equal(x.nodes['account-google'].hidden,false);});
test('public login stays a login form even when a previous signup is waiting',async()=>{const x=await ui('',{'/auth/email-config':{enabled:true,pendingEmail:'pending@example.com',retryAfter:40}},'/ar/login');assert.equal(x.nodes['account-title'].textContent,'تسجيل الدخول');assert.equal(x.nodes['account-form'].hidden,false);assert.equal(x.nodes['account-waiting'].hidden,true);assert.equal(x.nodes['account-phone'].disabled,true);assert.equal(x.nodes['account-forgot'].hidden,false);});

test('narrow mobile auth uses compact Turnstile and waits for a token before sending',async()=>{const x=await ui('',{'/auth/email-config':{enabled:true,captchaSiteKey:'public-test-site-key'}},'/ar/login',{captcha:true,width:264,theme:'light'});assert.equal(x.widgets[0].config.size,'compact');assert.equal(x.widgets[0].config.theme,'light');await x.nodes['account-form'].onsubmit({preventDefault(){}});assert.equal(x.calls.some(c=>c.url.endsWith('/signin')),false);assert.match(x.nodes['account-status'].textContent,/التحقق/);x.widgets[0].config.callback('test-only-captcha-token');await x.nodes['account-form'].onsubmit({preventDefault(){}});assert.equal(x.calls.find(c=>c.url.endsWith('/signin')).body.captchaToken,'test-only-captcha-token');});
test('slow configuration cannot submit an unprotected login request',async()=>{let finish;const ready=new Promise(resolve=>{finish=resolve;});const x=await ui('',{'/auth/email-config':()=>ready},'/en/login');await x.nodes['account-form'].onsubmit({preventDefault(){}});assert.equal(x.calls.some(c=>c.url.endsWith('/signin')),false);assert.match(x.nodes['account-status'].textContent,/getting ready/);finish({enabled:true});await new Promise(setImmediate);await x.nodes['account-form'].onsubmit({preventDefault(){}});assert.equal(x.calls.some(c=>c.url.endsWith('/signin')),true);});
test('failed mobile connection releases the submit button and retains entered fields',async()=>{const x=await ui('',{'/auth/email/signin':()=>{throw new Error('offline');}},'/ar/login');x.nodes['account-email'].value='example@example.com';await x.nodes['account-form'].onsubmit({preventDefault(){}});assert.equal(x.nodes['account-submit'].disabled,false);assert.equal(x.nodes['account-email'].value,'example@example.com');assert.equal(x.nodes['account-status'].textContent,'offline');});
