'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..');
async function ui(search='',responses={}){
 const nodes={};for(const [,id]of fs.readFileSync(path.join(root,'public/account.html'),'utf8').matchAll(/\bid="([^"]+)"/g))nodes[id]={id,hidden:false,disabled:false,required:false,value:'',checked:false,textContent:'',focus(){this.focused=true;}};
 const calls=[],redirects=[],window={};let interval;const context={document:{documentElement:{},getElementById:id=>nodes[id],head:{append(){}},createElement:()=>({})},window,location:{search,replace:url=>redirects.push(url)},URLSearchParams,Date,Set,setInterval:fn=>{interval=fn;},fetch:async(url,options)=>{calls.push({url,body:options&&JSON.parse(options.body)});const data=responses[url]??(url==='/auth/email-config'?{enabled:true}:{});return {ok:true,status:200,json:async()=>data};}};
 vm.runInNewContext(fs.readFileSync(path.join(root,'public/assets/account.js'),'utf8'),context);await new Promise(setImmediate);
 return {nodes,calls,redirects,interval};
}
test('signup requires profile and consent; signin hides and disables those fields',async()=>{const x=await ui('?mode=signup');for(const id of ['name','phone','terms','confirm-password'])assert.equal(x.nodes['account-'+id].required,true);x.nodes['account-signin'].onclick();for(const id of ['name','phone','terms','confirm-password'])assert.equal(x.nodes['account-'+id].disabled,true);assert.equal(x.nodes['account-password'].required,true);});
test('signup waits for verification, clears passwords and blocks immediate resend',async()=>{const x=await ui('?mode=signup',{'/auth/email/signup':{requiresConfirmation:true,email:'new@example.com',retryAfter:60}});Object.assign(x.nodes['account-email'],{value:'new@example.com'});x.nodes['account-password'].value=x.nodes['account-confirm-password'].value='safe_password_123';x.nodes['account-name'].value='Ahmed';x.nodes['account-phone'].value='+201012345678';x.nodes['account-terms'].checked=true;await x.nodes['account-form'].onsubmit({preventDefault(){}});assert.equal(x.nodes['account-form'].hidden,true);assert.equal(x.nodes['account-waiting'].hidden,false);assert.equal(x.nodes['account-resend'].disabled,true);assert.equal(x.nodes['account-password'].value,'');assert.deepEqual(x.redirects,[]);assert.equal(x.calls.find(c=>c.url.endsWith('/signup')).body.acceptTerms,true);x.nodes['account-confirmed-login'].onclick();assert.equal(x.nodes['account-waiting'].hidden,true);assert.equal(x.nodes['account-email'].value,'new@example.com');});
test('confirmation landing makes no verification request until explicit click',async()=>{const x=await ui('?mode=confirm',{'/auth/email/confirm':{redirect:'/auth/account?confirmed=1'}});assert.equal(x.calls.some(c=>c.url.endsWith('/confirm')),false);await x.nodes['account-form'].onsubmit({preventDefault(){}});assert.deepEqual(x.redirects,['/auth/account?confirmed=1']);});
test('Google profile completion prefills current user and preserves English layout',async()=>{const x=await ui('?mode=profile&lang=en',{'/auth/email/profile':{name:'Ahmed',contact_phone:'+201012345678'}});assert.equal(x.nodes['account-name'].value,'Ahmed');assert.equal(x.nodes['account-phone'].value,'+201012345678');assert.equal(x.nodes['account-google'].hidden,true);assert.equal(x.nodes['account-password'].disabled,true);assert.equal(x.nodes['account-privacy'].href,'/en/privacy');});
