const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const docs=require('../utils/support-knowledge');
function setup(result,fail=false){const c={module:{exports:{}},require:id=>id==='./support-knowledge'?docs:{callGemini:async()=>{if(fail)throw new Error('offline');return JSON.stringify(result);}}};vm.runInNewContext(fs.readFileSync(require.resolve('../utils/support.js'),'utf8'),c);return c.module.exports;}
test('approved topic returned; arbitrary model text never displayed',async()=>{const api=setup({scope:'help',topics:['cv'],text:'untrusted output',answer:'secret'});const r=await api.respond('ارفع السي في إزاي؟');assert.equal(r.articles[0].text,docs.find(d=>d.id==='cv').answer);assert(!JSON.stringify(r).includes('untrusted'));assert(!JSON.stringify(r).includes('secret'));});
test('out-of-scope selection refuses and exposes no articles',async()=>{const api=setup({scope:'outside',topics:['ai']});const r=await api.respond('اكتبلي برنامج');assert.equal(r.articles.length,0);assert.equal(r.text,api.OUTSIDE);});
test('unknown model identifiers and malformed results never render',async()=>{const api=setup({scope:'help',topics:['../../secrets']});const r=await api.respond('test');assert.equal(r.scope,'unclear');assert.equal(r.articles.length,0);});
test('provider failure gives local support fallback',async()=>{const r=await setup(null,true).respond('سؤال');assert.equal(r.mode,'local');assert.equal(r.scope,'unclear');assert.equal(r.articles.length,0);});
test('knowledge actions restricted to read-only navigation',()=>{const allowed=new Set(['tour','tickets','notifications','cv','companies','template','channels','send','report','ai','account']);assert(docs.every(d=>allowed.has(d.action)));assert.equal(new Set(docs.map(d=>d.id)).size,docs.length);});

test('English support fallback uses English product knowledge',async()=>{const r=await setup(null,true).respond('How do I upload a PDF CV?',{language:'en'});assert.equal(r.mode,'local');assert(r.articles.some(a=>a.id==='cv'));assert(r.articles.every(a=>!/[\u0600-\u06ff]/.test(a.title+a.text)));assert(!/[\u0600-\u06ff]/.test(r.text));});
test('English out-of-scope support keeps the same scope restriction',()=>{const r=setup(null).answer({scope:'outside',topics:['ai']},'en');assert.equal(r.scope,'outside');assert.equal(r.articles.length,0);assert.match(r.text,/only help with using Mrsaal/);});
test('every support topic has a bilingual title and guide',()=>{assert(docs.every(d=>typeof d.title_en==='string'&&d.title_en.length>0&&typeof d.answer_en==='string'&&d.answer_en.length>0));});
