const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
test('tour navigation, completion, replay, keyboard exit and inert cleanup',()=>{
 const nodes=new Map(),listeners={},tasks=[];let context;
 function node(id){if(nodes.has(id))return nodes.get(id);const n={id,style:{},hidden:false,inert:false,isConnected:true,disabled:false,tagName:'DIV',offsetHeight:240,offsetWidth:350,checked:false,events:{},getClientRects(){return this.hidden?[]:[{}]},getBoundingClientRect(){return {left:500,right:700,top:100,bottom:150}},closest(){return null},scrollIntoView(){},focus(){document.activeElement=this},addEventListener(k,fn){this.events[k]=fn},querySelector(s){return node(s)},querySelectorAll(){return ['close','back','next','manual'].map(node)},set innerHTML(v){this.html=v}};nodes.set(id,n);return n;}
 const app=node('app');const document={body:{children:[app],appendChild(n){this.children.push(n)}},activeElement:app,getElementById:node,createElement:()=>node('host'),querySelector(s){if(s==='.page.active')return {id:'page-home'};if(s==='.app.active')return app;return null},addEventListener(k,fn){listeners[k]=fn}};
 const data=new Map();context={document,currentUser:{email:'one@example.com'},localStorage:{getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)},getComputedStyle:()=>({visibility:'visible'}),innerWidth:1000,innerHeight:800,setTimeout:fn=>{tasks.push(fn);return tasks.length},clearTimeout(){},requestAnimationFrame:()=>1,cancelAnimationFrame(){}};context.MrsaalGuide=require('../public/assets/product-guide');context.window=context;context.addEventListener=()=>{};vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../public/assets/tour.js'),'utf8'),context);
 const tour=context.MrsaalTour;tour.start('home');assert.equal(app.inert,true);assert.equal(node('tour-title').textContent,'مساحة متابعتك');
 const click=action=>node('host').events.click({target:{closest:()=>({dataset:{tour:action}})}});
 click('next');assert.equal(node('tour-title').textContent,'الخطوة المناسبة دلوقتي');click('back');assert.equal(node('tour-title').textContent,'مساحة متابعتك');for(let i=0;i<context.MrsaalGuide.tours.home.length;i++)click('next');assert.equal(app.inert,false);assert.equal(JSON.parse([...data.values()][0]).home,'completed');assert.equal(document.activeElement,app);
 tour.start('home');assert.equal(app.inert,true);listeners.keydown({key:'Escape',preventDefault(){},stopImmediatePropagation(){}});assert.equal(app.inert,false);assert.equal(JSON.parse([...data.values()][0]).home,'skipped');
 tour.start('home');node('tour-manual').events.change({target:{checked:true}});tour.stop();tasks.at(-1)();assert.equal(app.inert,false);assert.equal(JSON.parse([...data.values()][0]).manualOnly,true);
});
