'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {isPDF,cvKind,textFile,spreadsheetRows,column}=require('../utils/upload-files');
test('mobile PDF identified by content with empty or generic MIME and no suffix',()=>{for(const mimetype of ['', 'application/octet-stream','application/pdf']){const file={originalname:'document',mimetype,buffer:Buffer.from('%PDF-1.7\nbody')};assert(isPDF(file));assert.equal(cvKind(file),'pdf');}});
test('fake PDF and unsupported binary CV rejected before storing data',()=>{assert.throws(()=>cvKind({originalname:'CV.pdf',mimetype:'application/pdf',buffer:Buffer.from('not a pdf')}));assert.throws(()=>cvKind({originalname:'CV.docx',buffer:Buffer.from('PK\x03\x04')}));});
test('Arabic UTF8 and UTF16 spreadsheet text decoded without mojibake',()=>{const text='شركة,إيميل,هاتف\nمرسال,test@example.com,01001234567';assert.equal(textFile(Buffer.from('\uFEFF'+text)),text);assert.equal(textFile(Buffer.concat([Buffer.from([255,254]),Buffer.from(text,'utf16le')])),text);assert.throws(()=>textFile(Buffer.from([0xc3,0x28])));});
test('CSV preserved as string and formatted spreadsheet values requested',()=>{let input,options,jsonOptions;const file={originalname:'شركات.csv',mimetype:'application/octet-stream',buffer:Buffer.from('اسم,هاتف\nشركة,01001234567')};const xlsx={read:(data,opts)=>{input=data;options=opts;return {SheetNames:['Sheet1'],Sheets:{Sheet1:{}}};},utils:{sheet_to_json:(_,opts)=>{jsonOptions=opts;return [['اسم','هاتف'],['شركة','01001234567']];}}};const r=spreadsheetRows(file,xlsx);assert.equal(typeof input,'string');assert.equal(options.raw,true);assert.equal(jsonOptions.raw,false);assert.equal(r.rows[1][1],'01001234567');});
test('column mapping rejects NaN, negative and out of range selections',()=>{for(const value of ['NaN','1x','-1','99'])assert.throws(()=>column(value,3));assert.throws(()=>column('',3,true));assert.equal(column('',3),-1);assert.equal(column('0',3,true),0);});
test('XLSX with mobile generic MIME detected from signature',()=>{let opts;const rows=spreadsheetRows({originalname:'download',mimetype:'application/octet-stream',buffer:Buffer.from([0x50,0x4b,3,4,1])},{read:(_,o)=>{opts=o;return {SheetNames:['first'],Sheets:{first:{}}};},utils:{sheet_to_json:()=>[['name'],['Company']]}});assert.equal(opts.type,'buffer');assert.equal(rows.rows.length,2);});
test('published tours and assistant share one approved guide and valid targets',()=>{const fs=require('node:fs'),path=require('node:path');const g=require('../public/assets/product-guide');assert.strictEqual(require('../utils/support-knowledge'),g.topics);const html=fs.readFileSync(path.join(__dirname,'../public/index.html'),'utf8');for(const steps of Object.values(g.tours))for(const s of steps)assert(html.includes('id="'+s.id+'"'),'missing tour target '+s.id);assert(g.tours.companies.length>=8);assert(g.tours['settings-ai'].length>=5);assert(html.includes('/assets/product-guide.js'));});
