'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {render}=require('../utils/site-template');
function load(file,deps){const context={module:{exports:{}},__dirname:path.dirname(path.join(__dirname,'..',file)),require:id=>deps[id]||require(id),process:{env:{}},console,Date,Set,URLSearchParams};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context);return context.module.exports;}
function harness(){const handlers=[];const r={use(...h){handlers.push({method:'use',h});},get(route,...h){handlers.push({method:'get',route,h});},post(route,...h){handlers.push({method:'post',route,h});},patch(route,...h){handlers.push({method:'patch',route,h});}};return {r,handlers};}
function response(){return {statusCode:200,headers:{},set(k,v){if(typeof k==='object')Object.assign(this.headers,k);else this.headers[k]=v;return this;},status(s){this.statusCode=s;return this;},send(x){this.body=x;return this;},json(x){this.body=x;return this;},redirect(x){this.location=x;return this;},sendFile(x){this.file=x;return this;}};}
test('bilingual pages have local assets, real links and no demo-only controls',()=>{for(const lang of ['ar','en'])for(const page of ['home','product','blog','plans','help','login','about','contact','privacy','terms']){const html=render(lang,page);assert(html.includes(`lang="${lang}"`));assert(html.startsWith('<!doctype html>'));assert(!html.includes('href="#'));assert(!html.includes('data-lucide'));assert(!html.includes('data-action="size"'));for(const asset of html.matchAll(/(?:src|href)="(\/assets\/[^"?]+)"/g))assert(fs.existsSync(path.join(__dirname,'../public',asset[1])));}assert(render('ar','login').includes('href="/auth/google"'));});
test('CMS titles, bodies and categories cannot inject HTML',()=>{const p={slug:'safe',category:'<img onerror=bad>',title_ar:'<script>alert(1)</script>',excerpt_ar:'" bad',body_ar:'<img src=x onerror=alert(1)>\n\nSecond paragraph'};const html=render('ar','article',{post:p});assert(!html.includes('<script>alert'));assert(!html.includes('<img src=x'));assert(html.includes('&lt;img'));assert(html.includes('<p>Second paragraph</p>'));assert(render('ar','blog',{posts:[p]}).includes('&lt;img onerror=bad&gt;'));});
test('suspended live sessions blocked, staff can administer during pause',async()=>{let staff=false;const a=load('utils/access-control.js',{'./db':{get:async sql=>sql.includes('FROM users')?{email:'me',suspended_at:new Date()}:{tool_paused:true}},'./helpdesk':{adminEmail:()=>staff}});await assert.rejects(a.checkToolAccess('u'),e=>e.status===403&&e.code==='ACCOUNT_SUSPENDED');staff=true;await a.checkToolAccess('u');});
test('maintenance blocks tool but leaves user tickets available',async()=>{const a=load('utils/access-control.js',{'./db':{get:async sql=>sql.includes('FROM users')?{email:'user'}:{tool_paused:true}},'./helpdesk':{adminEmail:()=>false}});await assert.rejects(a.checkToolAccess('u'),e=>e.status===503);let next=false;const res=response();await a.gate({session:{userId:'u'},path:'/api/tickets'},res,()=>{next=true});assert(next);await a.gate({session:{userId:'u'},path:'/api/email/send'},res,()=>assert.fail());assert.equal(res.statusCode,503);});
test('app requires login and permitted account; drafts return 404',async()=>{const h=harness();let permitted=true;load('routes/site.js',{express:{Router:()=>h.r},'../utils/db':{all:async()=>[],get:async()=>null},'../middleware/async-handler':f=>f,'../utils/site-template':{render,escapeHTML:v=>String(v)},'../utils/helpdesk':{isAdmin:async()=>false},'../utils/access-control':{checkToolAccess:async()=>{if(!permitted)throw Object.assign(new Error('Blocked'),{status:403});}}});const app=h.handlers.find(x=>x.route==='/app').h[0];let res=response();await app({session:{}},res);assert.equal(res.location,'/ar/login');res=response();await app({session:{userId:'u'}},res);assert(res.file.endsWith('index.html'));permitted=false;res=response();await app({session:{userId:'u'}},res);assert.equal(res.statusCode,403);assert(!res.file);const article=h.handlers.find(x=>x.route==='/:lang(ar|en)/blog/:slug').h[0];res=response();await article({params:{lang:'ar',slug:'draft'}},res);assert.equal(res.statusCode,404);});
test('admin API denies non-admin and unsigned mutation requests',async()=>{let staff=false;const h=harness();load('routes/admin.js',{express:{Router:()=>h.r},'../utils/db':{},'../utils/helpdesk':{isAdmin:async()=>staff,adminEmail:()=>false,quota:()=>true},'../middleware/async-handler':f=>f});const guard=h.handlers[0].h[0];await assert.rejects(guard({session:{userId:'u'},method:'GET'},response(),()=>assert.fail()),e=>e.status===403);staff=true;await assert.rejects(guard({session:{userId:'u'},method:'POST',get:()=>null,is:()=>false},response(),()=>assert.fail()),e=>e.status===403);});
test('suspension cancels pending sends transactionally and protects staff',async()=>{const h=harness(),writes=[];let email='user@example.com';const client={query:async(sql,args)=>{writes.push({sql,args});return {rowCount:1,rows:sql.startsWith('SELECT')?[{id:'u2',email}]:[]};},release(){}};load('routes/admin.js',{express:{Router:()=>h.r},'../utils/db':{pool:{connect:async()=>client}},'../utils/helpdesk':{isAdmin:async()=>true,adminEmail:e=>e==='admin@example.com',quota:()=>true},'../middleware/async-handler':f=>f});const change=h.handlers.find(x=>x.route==='/users/:id').h[0];await change({session:{userId:'staff'},params:{id:'u2'},body:{suspended:true,reason:'Review'}},response());assert(writes.some(x=>x.sql.includes("UPDATE scheduled_jobs SET status='cancelled'")));assert.equal(writes.at(-1).sql,'COMMIT');writes.length=0;email='admin@example.com';await assert.rejects(change({session:{userId:'staff'},params:{id:'u2'},body:{suspended:true}},response()));assert.equal(writes.at(-1).sql,'ROLLBACK');assert(!writes.some(x=>x.sql.startsWith('UPDATE')));});
test('startup migrations never overwrite administrator edits',async()=>{const sql=[];const schema=load('utils/website-schema.js',{'./db':{run:async s=>sql.push(s)}});await schema.ensureWebsiteSchema();assert(sql[0].includes('ADD COLUMN IF NOT EXISTS suspended_at'));assert.equal(sql.length,4);assert(sql.slice(1).every(s=>s.includes('ON CONFLICT(slug) DO NOTHING')));});
