const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const profile=require('../utils/writing-profile');
function engine(responses){const prompts=[];const box={module:{exports:{}},require:id=>id==='./ai-legacy'?{callGemini:async(p,t,k,m,valid)=>{prompts.push(p);const r=responses.shift();if(r instanceof Error)throw r;const txt=JSON.stringify(r);if(!valid(txt))throw new Error('invalid');return txt;}}:profile};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../utils/ai.js'),'utf8'),box);return {ai:box.module.exports,prompts};}
const draft={subject:'تواصل',body:'أهلًا، حابب أعرف لو عندكم فرص مناسبة.'};
const reviewed={...draft,notes:['راجع المسمى المطلوب.'],needsUserInput:false};
const args={cv:'أنا مطور React.',company:{name:'ألف',field:'برمجيات'},instructions:profile.encode(profile.defaults())};
test('profile round trip and legacy instructions retained',()=>{assert.deepEqual(profile.decode(profile.encode(profile.defaults())),profile.normalize(profile.defaults()));assert.equal(profile.decode('مصري').instructions,'مصري');assert.throws(()=>profile.normalize({language:'unknown'}));});
test('email draft reviewed; examples not factual sources',async()=>{const e=engine([draft,reviewed]);const r=await e.ai.generateEmail(args);assert.equal(r.body,reviewed.body);assert.equal(r.reviewed,true);assert.equal(e.prompts.length,2);assert.match(e.prompts[0],/أمثلة الكاتب مرجع الأسلوب فقط/);});
test('WhatsApp returns legacy string contract',async()=>{const e=engine([draft,reviewed]);assert.equal(await e.ai.generateWhatsAppMessage(args),draft.body);assert.match(e.prompts[0],/"channel":"whatsapp"/);});
test('review failure never silently emits an unchecked draft',async()=>{const e=engine([draft,new Error('provider offline')]);await assert.rejects(e.ai.generateEmail(args),/provider offline/);});
test('insufficient data blocked',async()=>{const e=engine([draft,{...reviewed,needsUserInput:true}]);await assert.rejects(e.ai.generateEmail(args),/معلومات/);});
test('fixed template makes zero calls and blocks missing vars',async()=>{const e=engine([]),p=profile.defaults();p.mode='template';p.email.template='أهلًا {company_name}';const r=await e.ai.generateEmail({...args,instructions:profile.encode(p),subjectTemplate:'تواصل'});assert.equal(r.body,'أهلًا ألف');assert.equal(e.prompts.length,0);p.email.template='{your_name}';await assert.rejects(e.ai.generateEmail({...args,instructions:profile.encode(p)}),/متغير/);});
test('style analysis needs examples; never mutates approved profile',async()=>{const e=engine([{summary:'مصري مباشر'}]),p=profile.defaults();await assert.rejects(e.ai.analyzeStyle(p,args));p.examples=['أهلًا','صباح الخير'];const r=await e.ai.analyzeStyle(p,args);assert.equal(r.summary,'مصري مباشر');assert.equal(p.summary,'');});
test('revision passes original draft and intent, without sending',async()=>{const e=engine([draft,reviewed]);await e.ai.generate({...args,revision:{action:'اختصر',draft}},'email');assert.match(e.prompts[0],/اختصر/);});
