'use strict';
const router=require('express').Router();const {randomUUID}=require('crypto');const {all,get,run,pool}=require('../utils/db');const {isAdmin,adminEmail,quota}=require('../utils/helpdesk');const wrap=require('../middleware/async-handler');
function fail(message,status=400){const e=new Error(message);e.status=status;throw e;}
function text(value,max,required=true){if(typeof value!=='string'||value.length>max||(required&&!value.trim()))fail('النص مفقود أو أطول من المسموح');return value.trim();}
router.use(wrap(async(req,res,next)=>{res.set('Cache-Control','no-store');if(!req.session?.userId)fail('سجّل الدخول',401);if(!await isAdmin(req.session.userId))fail('للإدارة فقط',403);if(req.method!=='GET'){
 if(req.get('X-Mrsaal-Admin')!=='1'||!req.is('application/json'))fail('طلب غير مسموح',403);
 if(!quota('admin:'+req.session.userId,120))fail('انتظر قبل المحاولة',429);
 }next();}));
router.get('/users',wrap(async(req,res)=>{const offset=Math.max(0,Math.min(100000,parseInt(req.query.offset)||0));const search=String(req.query.search||'').slice(0,100);const users=await all(`SELECT u.id,u.name,u.email,u.supabase_id,u.google_id,u.contact_phone,u.email_verified_at,u.profile_completed_at,u.registration_required,u.send_limit,u.ai_limit,u.suspended_at,u.suspension_reason,a.last_seen FROM users u LEFT JOIN support_activity a ON a.user_id=u.id WHERE u.email ILIKE $1 OR u.name ILIKE $1 ORDER BY u.created_at DESC,u.id LIMIT 50 OFFSET $2`,['%'+search+'%',offset]);res.json({users:users.map(u=>({...u,admin:adminEmail(u.email)})),offset});}));
router.patch('/users/:id',wrap(async(req,res)=>{
 if(typeof req.body.suspended!=='boolean')fail('اختار الحالة');const reason=text(req.body.reason||'',500,false);const client=await pool.connect();
 try{await client.query('BEGIN');const result=await client.query('SELECT id,email FROM users WHERE id=$1 FOR UPDATE',[req.params.id]);const target=result.rows[0];if(!target)fail('المستخدم غير موجود',404);if(adminEmail(target.email)||target.id===req.session.userId)fail('لا يمكن تعليق حساب الإدارة');
 await client.query('UPDATE users SET suspended_at=CASE WHEN $1 THEN NOW() ELSE NULL END,suspension_reason=$2 WHERE id=$3',[req.body.suspended,req.body.suspended?reason:null,target.id]);
 if(req.body.suspended){await client.query("UPDATE email_log SET status='cancelled',reason='تم إلغاء الجدولة لتعليق الحساب' WHERE id IN (SELECT log_id FROM scheduled_jobs WHERE user_id=$1 AND status='pending')",[target.id]);await client.query("UPDATE scheduled_jobs SET status='cancelled' WHERE user_id=$1 AND status='pending'",[target.id]);await client.query("UPDATE companies SET status='pending',scheduled_at=NULL WHERE user_id=$1 AND status='scheduled'",[target.id]);}
 await client.query('INSERT INTO admin_audit(actor_id,action,target_id) VALUES($1,$2,$3)',[req.session.userId,req.body.suspended?'suspend':'restore',target.id]);await client.query('COMMIT');res.json({ok:true});
 }catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
}));
router.get('/users/:id/usage',wrap(async(req,res)=>res.json(await all('SELECT kind,day,amount FROM usage_daily WHERE user_id=$1 ORDER BY day DESC LIMIT 60',[req.params.id]))));
router.patch('/users/:id/limits',wrap(async(req,res)=>{const {send,ai}=req.body;if(!Number.isInteger(send)||!Number.isInteger(ai)||send<0||ai<0||send>10000||ai>10000)fail('الحدود من صفر إلى 10000');await run('UPDATE users SET send_limit=$1,ai_limit=$2 WHERE id=$3',[send,ai,req.params.id]);await run('INSERT INTO admin_audit(actor_id,action,target_id) VALUES($1,$2,$3)',[req.session.userId,'update_limits',req.params.id]);res.json({ok:true});}));
router.get('/feedback',wrap(async(req,res)=>res.json(await all('SELECT f.id,f.user_id,u.email,f.channel,f.rating,f.note,f.created_at FROM ai_feedback f JOIN users u ON u.id=f.user_id ORDER BY f.created_at DESC LIMIT 50'))));
router.get('/posts',wrap(async(req,res)=>res.json({posts:await all('SELECT * FROM website_posts ORDER BY updated_at DESC LIMIT 200')})));
router.post('/posts',wrap(async(req,res)=>{const b=req.body;const slug=text(b.slug,120);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))fail('الرابط يحتاج حروف إنجليزية صغيرة وأرقام وشرطات');if(!['draft','published'].includes(b.status))fail('حالة المقال غير صالحة');const values=[b.id?text(b.id,120):randomUUID(),slug,text(b.title_ar,200),text(b.title_en,200),text(b.excerpt_ar,500),text(b.excerpt_en,500),text(b.body_ar,40000),text(b.body_en,40000),text(b.category||'',80,false),b.status];if(b.id&&!await get('SELECT id FROM website_posts WHERE id=$1',[b.id]))fail('المقال غير موجود',404);
 await run(`INSERT INTO website_posts(id,slug,title_ar,title_en,excerpt_ar,excerpt_en,body_ar,body_en,category,status,published_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,CASE WHEN $10='published' THEN NOW() ELSE NULL END) ON CONFLICT(id) DO UPDATE SET slug=EXCLUDED.slug,title_ar=EXCLUDED.title_ar,title_en=EXCLUDED.title_en,excerpt_ar=EXCLUDED.excerpt_ar,excerpt_en=EXCLUDED.excerpt_en,body_ar=EXCLUDED.body_ar,body_en=EXCLUDED.body_en,category=EXCLUDED.category,status=EXCLUDED.status,published_at=CASE WHEN EXCLUDED.status='published' THEN COALESCE(website_posts.published_at,NOW()) ELSE NULL END,updated_at=NOW()`,values);await run('INSERT INTO admin_audit(actor_id,action,target_id) VALUES($1,$2,$3)',[req.session.userId,'save_post',values[0]]);res.json({id:values[0]});}));
router.get('/settings',wrap(async(req,res)=>res.json(await get('SELECT tool_paused,notice FROM website_settings WHERE id=1'))));
router.patch('/settings',wrap(async(req,res)=>{if(typeof req.body.tool_paused!=='boolean')fail('إعداد غير صالح');const notice=text(req.body.notice||'',500,false);await run('UPDATE website_settings SET tool_paused=$1,notice=$2 WHERE id=1',[req.body.tool_paused,notice]);await run('INSERT INTO admin_audit(actor_id,action) VALUES($1,$2)',[req.session.userId,'update_settings']);res.json({ok:true});}));
router.get('/audit',wrap(async(req,res)=>res.json({events:await all('SELECT a.action,a.target_id,a.created_at,u.email FROM admin_audit a JOIN users u ON u.id=a.actor_id ORDER BY a.created_at DESC LIMIT 100')})));
module.exports=router;
