'use strict';
const router=require('express').Router(),{randomUUID}=require('crypto');const {get,all,run,pool}=require('../utils/db');const wrap=require('../middleware/async-handler');
router.use(require('../middleware/auth').requireAuth);
router.get('/',wrap(async(req,res)=>res.json(await all(`SELECT c.*,(SELECT jsonb_object_agg(status,n) FROM (SELECT status,COUNT(*) n FROM campaign_items WHERE campaign_id=c.id GROUP BY status) s) AS counts FROM campaigns c WHERE user_id=$1 ORDER BY created_at DESC LIMIT 50`,[req.session.userId]))));
router.post('/',wrap(async(req,res)=>{
 const userId=req.session.userId,{companyIds,channel}=req.body;if(!Array.isArray(companyIds)||!companyIds.length||companyIds.length>500||companyIds.some(id=>typeof id!=='string'||id.length>160)||!['email','whatsapp'].includes(channel))return res.status(400).json({error:'اختار قناة ومن 1 إلى 500 شركة'});
 const cv=await require('../utils/cv-store').active(userId);if(!cv)return res.status(400).json({error:'ضيف السيرة أولًا'});
 const account=channel==='email'?await require('../utils/gmail-accounts').resolveAccount(userId,req.body.senderAccountId):null;
 const client=await pool.connect();const id=randomUUID();try{await client.query('BEGIN');await client.query(`INSERT INTO campaigns(id,user_id,channel,sender_account_id,cv_id,delay_seconds) VALUES($1,$2,$3,$4,$5,$6)`,[id,userId,channel,account?.gmail_account_id||null,cv.id,Math.floor(Math.min(300,Math.max(5,Number(req.body.delaySeconds)||5)))]);
 for(const companyId of new Set(companyIds)){const co=(await client.query('SELECT * FROM companies WHERE id=$1 AND user_id=$2',[companyId,userId])).rows[0];if(!co)continue;const reason=require('../utils/delivery-channel').skipReason(co,channel);const draft=(await client.query('SELECT subject,body FROM message_drafts WHERE user_id=$1 AND company_id=$2 AND channel=$3',[userId,companyId,channel])).rows[0];await client.query('INSERT INTO campaign_items(id,campaign_id,company_id,company_name,recipient,subject,body,status,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[randomUUID(),id,co.id,co.name,channel==='email'?co.email:co.phone,draft?.subject||'',draft?.body||'',reason?'skipped':'draft',reason||null]);}
 await client.query('COMMIT');res.json({ok:true,id});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
}));
router.get('/:id',wrap(async(req,res)=>{const campaign=await get('SELECT * FROM campaigns WHERE id=$1 AND user_id=$2',[req.params.id,req.session.userId]);if(!campaign)return res.status(404).json({error:'الحملة غير موجودة'});res.json({campaign,items:await all('SELECT * FROM campaign_items WHERE campaign_id=$1 ORDER BY company_name,id',[campaign.id])});}));
router.post('/:id/items/:item/generate',wrap(async(req,res)=>{const c=await get("SELECT * FROM campaigns WHERE id=$1 AND user_id=$2 AND status IN ('draft','paused')",[req.params.id,req.session.userId]);if(!c)return res.status(409).json({error:'الحملة غير قابلة للتعديل'});const item=await get("SELECT * FROM campaign_items WHERE id=$1 AND campaign_id=$2 AND status IN ('draft','ready')",[req.params.item,c.id]);if(!item)return res.status(404).json({error:'المسودة غير موجودة'});const company=await get('SELECT * FROM companies WHERE id=$1 AND user_id=$2',[item.company_id,req.session.userId]);const cv=await require('../utils/cv-store').active(req.session.userId,c.cv_id);const t=await get('SELECT * FROM templates WHERE user_id=$1 ORDER BY created_at DESC LIMIT 1',[req.session.userId]);if(!company||!cv)throw new Error('راجع الشركة والسيرة');const claim=await run("UPDATE campaign_items i SET status='generating' FROM campaigns c WHERE i.id=$1 AND i.campaign_id=c.id AND c.status IN ('draft','paused') AND i.status IN ('draft','ready')",[item.id]);if(!claim.rowCount)return res.status(409).json({error:'المسودة قيد التنفيذ'});let result;try{result=await require('../utils/ai').generate({userId:req.session.userId,cv:cv.content,company,instructions:t?.instructions,subjectTemplate:t?.subject_template},c.channel);}catch(e){await run("UPDATE campaign_items SET status='draft' WHERE id=$1 AND status='generating'",[item.id]);throw e;}await run("UPDATE campaign_items SET subject=$1,body=$2,status='draft',updated_at=NOW() WHERE id=$3 AND status='generating'",[result.subject||'',result.body,item.id]);res.json(result);}));
router.patch('/:id/items/:item',wrap(async(req,res)=>{const {subject='',body}=req.body;if(typeof body!=='string'||!body.trim()||body.length>14000||typeof subject!=='string'||subject.length>240||/[\r\n]/.test(subject))return res.status(400).json({error:'راجع المسودة'});const result=await run(`UPDATE campaign_items i SET subject=$1,body=$2,status='ready',updated_at=NOW() FROM campaigns c WHERE i.id=$3 AND i.campaign_id=c.id AND c.id=$4 AND c.user_id=$5 AND c.status IN ('draft','paused') AND i.status IN ('draft','ready')`,[subject,body,req.params.item,req.params.id,req.session.userId]);if(!result.rowCount)return res.status(409).json({error:'لا يمكن تعديل هذا العنصر الآن'});res.json({ok:true});}));
router.post('/:id/:action',wrap(async(req,res)=>{
 const {action,id}=req.params;const scheduled=req.body.scheduledAt;if(scheduled&&(typeof scheduled!=='string'||!Number.isFinite(new Date(scheduled).getTime())||new Date(scheduled).getTime()<=Date.now()))return res.status(400).json({error:'اختار موعدًا صحيحًا في المستقبل'});if(!['start','pause','resume','cancel'].includes(action))return res.status(400).json({error:'إجراء غير معروف'});
 const userId=req.session.userId;const c=await get('SELECT * FROM campaigns WHERE id=$1 AND user_id=$2',[id,userId]);if(!c)return res.status(404).json({error:'الحملة غير موجودة'});
 if(['start','resume'].includes(action)){if(!['draft','paused'].includes(c.status))return res.status(409).json({error:'الحملة غير قابلة للبدء'});if(await get("SELECT id FROM campaign_items WHERE campaign_id=$1 AND status NOT IN ('ready','skipped','sent','failed','uncertain','cancelled') LIMIT 1",[id]))return res.status(409).json({error:'راجع واعتمد كل المسودات أولًا'});await require('../utils/access-control').checkToolAccess(userId);await run("UPDATE campaigns SET status='running',next_at=COALESCE($1::timestamptz,NOW()) WHERE id=$2 AND user_id=$3 AND status IN ('draft','paused') AND NOT EXISTS(SELECT 1 FROM campaign_items WHERE campaign_id=$2 AND status IN ('draft','generating'))",[req.body.scheduledAt?new Date(req.body.scheduledAt).toISOString():null,id,userId]);}
 else{await run('UPDATE campaigns SET status=$1 WHERE id=$2 AND user_id=$3 AND status IN (\'draft\',\'paused\',\'running\')',[action==='pause'?'paused':'cancelled',id,userId]);if(action==='cancel')await run("UPDATE campaign_items SET status='cancelled' WHERE campaign_id=$1 AND status IN ('draft','ready','generating')",[id]);}
 res.json({ok:true});
}));
module.exports=router;
