'use strict';
const router=require('express').Router(),wrap=require('../middleware/async-handler');const {get,all,run,pool}=require('../utils/db');
router.use(require('../middleware/auth').requireAuth);router.use((req,res,next)=>{res.set('Cache-Control','no-store');if(req.method!=='GET'&&req.get('X-Mrsaal-Launch')!=='1')return res.status(403).json({error:'طلب غير مسموح'});next();});
router.get('/usage',wrap(async(req,res)=>res.json({limits:await get('SELECT send_limit,ai_limit FROM users WHERE id=$1',[req.session.userId]),today:await all('SELECT kind,amount FROM usage_daily WHERE user_id=$1 AND day=CURRENT_DATE',[req.session.userId])})));
router.patch('/companies/:id',wrap(async(req,res)=>{const b=req.body;if(typeof b.notes!=='string'||b.notes.length>5000||typeof b.listName!=='string'||b.listName.length>80||!['not_started','applied','follow_up','interview','offer','rejected','closed'].includes(b.status))return res.status(400).json({error:'راجع بيانات المتابعة'});const remindAt=b.remindAt?new Date(b.remindAt).getTime():null;if(remindAt!==null&&(!Number.isFinite(remindAt)||remindAt<Date.now()))return res.status(400).json({error:'اختار موعدًا قادمًا'});const result=await run('UPDATE companies SET list_name=$1,notes=$2,followup_status=$3,remind_at=$4,reminder_sent=false WHERE id=$5 AND user_id=$6',[b.listName,b.notes,b.status,remindAt,req.params.id,req.session.userId]);if(!result.rowCount)return res.status(404).json({error:'الشركة غير موجودة'});res.json({ok:true});}));
router.get('/export',wrap(async(req,res)=>{const id=req.session.userId,data={exportedAt:new Date().toISOString(),user:await get('SELECT id,email,name,created_at FROM users WHERE id=$1',[id])};for(const table of ['companies','email_log','templates','message_drafts','ai_feedback','support_tickets','campaigns'])data[table]=await all(`SELECT * FROM ${table} WHERE user_id=$1`,[id]);data.campaign_items=await all('SELECT i.* FROM campaign_items i JOIN campaigns c ON c.id=i.campaign_id WHERE c.user_id=$1',[id]);data.cv_profiles=(await all('SELECT * FROM cv_profiles WHERE user_id=$1',[id])).map(c=>({...c,pdf_data:c.pdf_data?Buffer.from(c.pdf_data).toString('base64'):null}));data.gmail_accounts=await all('SELECT id,email,name,connected FROM gmail_accounts WHERE user_id=$1',[id]);data.ai_connections=await all('SELECT provider,selected_models,enabled,priority FROM ai_connections WHERE user_id=$1',[id]);res.set('Content-Disposition','attachment; filename="mrsaal-data.json"');res.json(data);}));
router.post('/delete',wrap(async(req,res)=>{
 const id=req.session.userId;if(req.body.confirm!=='DELETE')return res.status(400).json({error:'اكتب DELETE للتأكيد'});if(await require('../utils/helpdesk').isAdmin(id)||await get('SELECT id FROM admin_audit WHERE actor_id=$1 LIMIT 1',[id]))return res.status(409).json({error:'حساب الإدارة له سجل تدقيق؛ تواصل مع مسؤول السيرفر لحذفه.'});
 if(await get("SELECT id FROM delivery_attempts WHERE user_id=$1 AND status='processing' UNION SELECT id FROM campaigns WHERE user_id=$1 AND status='running' LIMIT 1",[id]))return res.status(409).json({error:'أوقف الحملات وانتظر اكتمال الإرسال الجاري قبل الحذف.'});
 const user=await get('SELECT supabase_id FROM users WHERE id=$1',[id]);if(user.supabase_id&&!process.env.SUPABASE_SERVICE_ROLE_KEY)return res.status(503).json({error:'الحذف الكامل يحتاج تفعيل مفتاح إدارة Supabase على الخادم. تواصل مع الدعم.'});
 // Revoke channels first. A revocation failure keeps the local account available to retry.
 for(const account of await all('SELECT * FROM gmail_accounts WHERE user_id=$1 AND connected=true',[id]))await require('../utils/revoke-google').revoke(account);
 await require('../utils/whatsapp').disconnect(id,true);
 if(user.supabase_id){const response=await fetch(new URL(process.env.SUPABASE_URL).origin+'/auth/v1/admin/users/'+encodeURIComponent(user.supabase_id),{method:'DELETE',headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY},signal:AbortSignal.timeout(15000)});if(!response.ok&&response.status!==404)throw new Error('تعذر حذف هوية Supabase. حاول لاحقًا');}
 const client=await pool.connect();try{await client.query('BEGIN');const tables=(await client.query("SELECT table_name FROM information_schema.columns WHERE table_schema='public' AND column_name='user_id' ORDER BY table_name")).rows;
 // Tables are discovered from PostgreSQL's own catalog; quote identifiers explicitly.
 const quote=x=>'"'+x.replace(/"/g,'""')+'"';
 await client.query('DELETE FROM support_messages WHERE user_id=$1 OR ticket_id IN (SELECT id FROM support_tickets WHERE user_id=$1)',[id]);
 for(const t of tables.filter(t=>!['support_tickets','support_messages','companies','users'].includes(t.table_name)))await client.query('DELETE FROM '+quote(t.table_name)+' WHERE user_id=$1',[id]);
 await client.query('DELETE FROM support_tickets WHERE user_id=$1',[id]);await client.query('DELETE FROM companies WHERE user_id=$1',[id]);await client.query("DELETE FROM session WHERE sess->>'userId'=$1",[id]);await client.query('DELETE FROM users WHERE id=$1',[id]);await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
 req.session.destroy(()=>res.json({ok:true}));
}));
module.exports=router;
