'use strict';
const router=require('express').Router();const {requireAuth}=require('../middleware/auth');const wrap=require('../middleware/async-handler');const {all,get,run}=require('../utils/db');const {seal,unseal}=require('../utils/connection-secrets');const {PROVIDERS,provider,listModels,generate}=require('../utils/ai-providers');
router.use(requireAuth);router.use((req,res,next)=>{res.set('Cache-Control','no-store');next();});
const busy=new Set(),windows=new Map();router.use((req,res,next)=>{if(req.method==='GET')return next();const id=req.session.userId,now=Date.now();for(const [k,v]of windows)if(now-v.time>3600000)windows.delete(k);const w=windows.get(id)||{time:now,count:0};if(w.count>=60||busy.has(id))return res.status(429).json({error:'استنى الطلب الحالي أو حاول لاحقًا؛ الحد 60 طلبًا في الساعة.'});w.count++;windows.set(id,w);busy.add(id);res.on('finish',()=>busy.delete(id));res.on('close',()=>busy.delete(id));next();});
router.get('/',wrap(async(req,res)=>{const rows=await all('SELECT provider,models,selected_models,enabled,priority,free_only FROM ai_connections WHERE user_id=$1 ORDER BY priority,provider',[req.session.userId]);res.json({providers:Object.entries(PROVIDERS).map(([id,p])=>({id,name:p.name,...rows.find(r=>r.provider===id),configured:rows.some(r=>r.provider===id)}))});}));
async function credentials(req){provider(req.params.provider);const row=await get('SELECT * FROM ai_connections WHERE user_id=$1 AND provider=$2',[req.session.userId,req.params.provider]);const supplied=req.body.key;if(supplied!=null&&(typeof supplied!=='string'||supplied.length>4096))throw new Error('المفتاح غير صالح');const key=supplied?.trim()||(row?unseal(row.credentials).key:null);if(!key)throw new Error('أضف مفتاح المنصة');return {row,key};}
router.post('/:provider/discover',wrap(async(req,res)=>{const {row,key}=await credentials(req);const freeOnly=req.body.freeOnly!==false;const models=await listModels(req.params.provider,key,freeOnly);res.json({models,selectedModels:row?.selected_models||[],message:'تم جلب قائمة الموديلات. اختبر الموديل قبل استخدامه؛ القائمة لا تضمن الرصيد أو صلاحية التوليد.'});}));
router.post('/:provider/save',wrap(async(req,res)=>{const {key}=await credentials(req),id=req.params.provider;const selected=req.body.models;if(!Array.isArray(selected)||selected.length>3||selected.some(x=>typeof x!=='string')||new Set(selected).size!==selected.length)return res.status(400).json({error:'اختار حتى 3 موديلات مختلفة بالترتيب'});const models=await listModels(id,key,req.body.freeOnly!==false);if(selected.some(x=>!models.some(m=>m.id===x)))return res.status(400).json({error:'موديل غير موجود في القائمة الحالية'});const priority=Number(req.body.priority);if(!Number.isInteger(priority)||priority<1||priority>99)return res.status(400).json({error:'الترتيب من 1 إلى 99'});if(req.body.enabled&&!selected.length)return res.status(400).json({error:'اختار موديلًا قبل التفعيل'});await run(`INSERT INTO ai_connections(user_id,provider,credentials,models,selected_models,enabled,priority,free_only) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(user_id,provider) DO UPDATE SET credentials=EXCLUDED.credentials,models=EXCLUDED.models,selected_models=EXCLUDED.selected_models,enabled=EXCLUDED.enabled,priority=EXCLUDED.priority,free_only=EXCLUDED.free_only`,[req.session.userId,id,seal({key}),JSON.stringify(models),JSON.stringify(selected),!!req.body.enabled,priority,req.body.freeOnly!==false]);res.json({ok:true});}));
router.post('/:provider/test',wrap(async(req,res)=>{const {key}=await credentials(req),model=req.body.model;if(typeof model!=='string'||!model)return res.status(400).json({error:'اختار الموديل'});const models=await listModels(req.params.provider,key,req.body.freeOnly!==false);if(!models.some(m=>m.id===model))return res.status(400).json({error:'الموديل غير متاح'});try{await generate(req.params.provider,key,model,'Reply with the single word OK.',128);require('../utils/ai-health').success(req.params.provider,key,model);}catch(e){require('../utils/ai-health').failed(req.params.provider,key,model,e.code,e.retryAfterMs);throw e;}res.json({ok:true,message:'الموديل استجاب بنجاح الآن.'});}));
router.post('/:provider/remove',wrap(async(req,res)=>{provider(req.params.provider);await run('DELETE FROM ai_connections WHERE user_id=$1 AND provider=$2',[req.session.userId,req.params.provider]);res.json({ok:true});}));
module.exports=router;
