'use strict';
const router=require('express').Router(),wrap=require('../middleware/async-handler'),sb=require('../utils/supabase-auth');const {get,run}=require('../utils/db'),{seal,unseal}=require('../utils/connection-secrets'),{quota}=require('../utils/helpdesk'),registration=require('../utils/registration');
const save=req=>new Promise((resolve,reject)=>req.session.save(e=>e?reject(e):resolve()));
router.get('/email-config',(req,res)=>{res.set('Cache-Control','no-store');res.json({enabled:sb.configured(),captchaSiteKey:process.env.TURNSTILE_SITE_KEY||null,pendingEmail:req.session.pendingSignup?.until>Date.now()?req.session.pendingSignup.email:null,retryAfter:Math.max(0,Math.ceil(((req.session.pendingSignup?.sentAt||0)+60000-Date.now())/1000))});});
router.get('/account',(req,res)=>{res.set({'Cache-Control':'no-store','X-Robots-Tag':'noindex'});res.sendFile(require('path').join(__dirname,'../public/account.html'));});
router.use('/email',(req,res,next)=>{res.set('Cache-Control','no-store');if(req.method==='POST'){if(req.get('X-Mrsaal-Auth')!=='1'||!req.is('application/json'))return res.status(403).json({error:'طلب غير مسموح'});if(!quota('auth:'+req.ip,60))return res.status(429).json({error:'محاولات كثيرة. حاول لاحقًا.'});}next();});
function credentials(body,checkPassword=true){const email=String(body.email||'').trim().toLowerCase(),password=body.password;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254||checkPassword&&(typeof password!=='string'||password.length<8||password.length>128))registration.fail('اكتب بريدًا صحيحًا وكلمة مرور من 8 إلى 128 حرفًا');return {email,password};}
async function login(req,id){await require('../utils/access-control').checkToolAccess(id,true);await new Promise((resolve,reject)=>req.session.regenerate(e=>e?reject(e):resolve()));req.session.userId=id;await save(req);}
router.post('/email/signup',wrap(async(req,res)=>{const body=credentials(req.body),details=registration.profile(req.body);if(req.body.confirmPassword!==body.password)registration.fail('كلمتا المرور غير متطابقتين.');if(req.body.website)registration.fail('تعذر إنشاء الحساب.');const challenge=registration.captcha(req.body);await sb.confirmationRequired();await registration.emailLimit(body.email,req.ip);const data=await sb.request('/signup',{...body,...challenge,data:{...details,accepted_terms:true}});if(data?.access_token)registration.fail('فعّل Confirm email في Supabase قبل السماح بالتسجيل.',503);req.session.pendingSignup={email:body.email,sentAt:Date.now(),until:Date.now()+86400000};await save(req);res.json({ok:true,requiresConfirmation:true,email:body.email,retryAfter:60,message:'افتح رابط التأكيد اللي وصلك على بريدك، وبعدها سجّل الدخول.'});}));
router.post('/email/resend',wrap(async(req,res)=>{const {email}=credentials(req.body,false),challenge=registration.captcha(req.body);await sb.confirmationRequired();await registration.emailLimit(email,req.ip);await sb.request('/resend',{type:'signup',email,...challenge});req.session.pendingSignup={email,sentAt:Date.now(),until:Date.now()+86400000};await save(req);res.json({ok:true,retryAfter:60,message:'لو البريد يحتاج تأكيد، هتوصلك رسالة جديدة. راجع الوارد والسبام.'});}));
router.post('/email/signin',wrap(async(req,res)=>{await sb.confirmationRequired();const data=await sb.request('/token?grant_type=password',{...credentials(req.body),...registration.captcha(req.body)});const user=await sb.identity(data.access_token),id=await sb.localUser(user);await login(req,id);const profile=await get('SELECT registration_required FROM users WHERE id=$1',[id]);res.json({ok:true,redirect:profile?.registration_required?'/auth/account?mode=profile':'/'});}));
router.post('/email/forgot',wrap(async(req,res)=>{const {email}=credentials(req.body,false),challenge=registration.captcha(req.body);await registration.emailLimit(email,req.ip);await sb.request('/recover',{email,...challenge});res.json({ok:true,message:'لو الحساب موجود، هتوصلك رسالة استعادة كلمة المرور.'});}));
router.post('/email/link',wrap(async(req,res)=>{if(!req.session.userId)return res.status(401).json({error:'سجل الدخول أولًا'});await sb.confirmationRequired();const data=await sb.request('/token?grant_type=password',{...credentials(req.body),...registration.captcha(req.body)}),user=await sb.identity(data.access_token),local=await get('SELECT email,supabase_id FROM users WHERE id=$1',[req.session.userId]);if(!local||local.email.toLowerCase()!==user.email.toLowerCase())return res.status(409).json({error:'لازم نفس بريد حسابك الحالي'});const exists=await get('SELECT id FROM users WHERE supabase_id=$1 AND id<>$2',[user.id,req.session.userId]);if(exists)return res.status(409).json({error:'تسجيل البريد مربوط بحساب مختلف'});await run('UPDATE users SET supabase_id=$1,email_verified_at=$2 WHERE id=$3',[user.id,user.email_confirmed_at,req.session.userId]);res.json({ok:true,message:'اتربط تسجيل البريد بحسابك الحالي.'});}));
router.get('/confirm',wrap(async(req,res)=>{const type=req.query.type,hash=req.query.token_hash;if(!['signup','recovery','email'].includes(type)||typeof hash!=='string'||!/^[a-zA-Z0-9_-]{20,300}$/.test(hash))return res.redirect('/auth/account?linkError=1');req.session.pendingConfirmation={hash,type,until:Date.now()+900000};await save(req);res.redirect('/auth/account?mode=confirm');}));
router.post('/email/confirm',wrap(async(req,res)=>{const pending=req.session.pendingConfirmation;if(!pending||pending.until<Date.now())registration.fail('الرابط انتهى أو غير صالح. اطلب رسالة جديدة.',400,'LINK_EXPIRED');const data=await sb.request('/verify',{token_hash:pending.hash,type:pending.type});await sb.identity(data.access_token);const type=pending.type;delete req.session.pendingConfirmation;delete req.session.pendingSignup;if(type==='recovery'){await new Promise((resolve,reject)=>req.session.regenerate(e=>e?reject(e):resolve()));req.session.passwordRecovery={token:seal({access_token:data.access_token}),until:Date.now()+600000};}await save(req);res.json({ok:true,redirect:type==='recovery'?'/auth/account?mode=reset':'/auth/account?confirmed=1'});}));
router.post('/email/password',wrap(async(req,res)=>{const recovery=req.session.passwordRecovery;if(!recovery||recovery.until<Date.now())return res.status(403).json({error:'افتح رابط الاستعادة من بريدك أولًا'});const password=req.body.password;if(typeof password!=='string'||password.length<8||password.length>128)registration.fail('كلمة المرور من 8 إلى 128 حرفًا');if(req.body.confirmPassword!==password)registration.fail('كلمتا المرور غير متطابقتين.');const token=unseal(recovery.token).access_token,user=await sb.identity(token);await sb.request('/user',{password},token,'PUT');const local=await get('SELECT id FROM users WHERE supabase_id=$1',[user.id]);if(local)await run("DELETE FROM session WHERE sess->>'userId'=$1",[local.id]);delete req.session.passwordRecovery;await save(req);res.json({ok:true,message:'اتغيرت كلمة المرور. سجل الدخول بالكلمة الجديدة.'});}));
router.get('/email/profile',wrap(async(req,res)=>{if(!req.session.userId)return res.status(401).json({error:'سجل الدخول أولًا'});const user=await get('SELECT name,email,contact_phone,registration_required FROM users WHERE id=$1',[req.session.userId]);res.json(user);}));
router.post('/email/profile',wrap(async(req,res)=>{if(!req.session.userId)return res.status(401).json({error:'سجل الدخول أولًا'});const details=registration.profile(req.body);await run('UPDATE users SET name=$1,contact_phone=$2,profile_completed_at=NOW(),terms_accepted_at=COALESCE(terms_accepted_at,NOW()),registration_required=false WHERE id=$3',[details.name,details.phone,req.session.userId]);res.json({ok:true,redirect:'/'});}));
module.exports=router;
