'use strict';
const router=require('express').Router(),wrap=require('../middleware/async-handler');const sb=require('../utils/supabase-auth');const {get,run}=require('../utils/db');const {seal,unseal}=require('../utils/connection-secrets');const {quota}=require('../utils/helpdesk');
router.get('/email-config',(req,res)=>res.json({enabled:sb.configured()}));
router.get('/account',(req,res)=>res.sendFile(require('path').join(__dirname,'../public/account.html')));
router.use('/email',(req,res,next)=>{res.set('Cache-Control','no-store');if(req.method==='POST'){if(req.get('X-Mrsaal-Auth')!=='1'||!req.is('application/json'))return res.status(403).json({error:'طلب غير مسموح'});if(!quota('auth:'+req.ip,20))return res.status(429).json({error:'محاولات كثيرة. حاول لاحقًا.'});}next();});
function credentials(body,checkPassword=true){const email=String(body.email||'').trim().toLowerCase(),password=body.password;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254||checkPassword&&(typeof password!=='string'||password.length<8||password.length>128)){const e=new Error('اكتب بريدًا صحيحًا وكلمة مرور من 8 إلى 128 حرفًا');e.status=400;throw e;}return {email,password};}
async function login(req,id){await require('../utils/access-control').checkToolAccess(id);await new Promise((resolve,reject)=>req.session.regenerate(e=>e?reject(e):resolve()));req.session.userId=id;await new Promise((resolve,reject)=>req.session.save(e=>e?reject(e):resolve()));}
router.post('/email/signup',wrap(async(req,res)=>{const body=credentials(req.body);await sb.request('/signup',{...body,data:{name:String(req.body.name||'').slice(0,120)}});res.json({ok:true,message:'لو البريد متاح، هتوصلك رسالة تأكيد. افتحها ثم سجّل الدخول.'});}));
router.post('/email/signin',wrap(async(req,res)=>{const data=await sb.request('/token?grant_type=password',credentials(req.body));const user=await sb.identity(data.access_token);await login(req,await sb.localUser(user));res.json({ok:true});}));
router.post('/email/forgot',wrap(async(req,res)=>{const {email}=credentials(req.body,false);await sb.request('/recover',{email});res.json({ok:true,message:'لو الحساب موجود، هتوصلك رسالة استعادة كلمة المرور.'});}));
router.post('/email/link',wrap(async(req,res)=>{if(!req.session.userId)return res.status(401).json({error:'سجل الدخول أولًا'});const data=await sb.request('/token?grant_type=password',credentials(req.body));const user=await sb.identity(data.access_token);const local=await get('SELECT email,supabase_id FROM users WHERE id=$1',[req.session.userId]);if(local.email.toLowerCase()!==user.email.toLowerCase())return res.status(409).json({error:'لازم نفس بريد حسابك الحالي'});const exists=await get('SELECT id FROM users WHERE supabase_id=$1 AND id<>$2',[user.id,req.session.userId]);if(exists)return res.status(409).json({error:'تسجيل البريد مربوط بحساب مختلف'});await run('UPDATE users SET supabase_id=$1 WHERE id=$2',[user.id,req.session.userId]);res.json({ok:true,message:'اتربط تسجيل البريد بحسابك الحالي.'});}));
router.get('/confirm',wrap(async(req,res)=>{
 const type=req.query.type,hash=req.query.token_hash;if(!['signup','recovery','email'].includes(type)||typeof hash!=='string'||! /^[a-zA-Z0-9_-]{20,300}$/.test(hash))return res.status(400).send('Invalid confirmation link');
 const data=await sb.request('/verify',{token_hash:hash,type});await sb.identity(data.access_token);
 if(type==='recovery'){req.session.passwordRecovery={token:seal({access_token:data.access_token}),until:Date.now()+600000};await new Promise((resolve,reject)=>req.session.save(e=>e?reject(e):resolve()));res.redirect('/auth/account?mode=reset');}else res.redirect('/auth/account?confirmed=1');
}));
router.post('/email/password',wrap(async(req,res)=>{const recovery=req.session.passwordRecovery;if(!recovery||recovery.until<Date.now())return res.status(403).json({error:'افتح رابط الاستعادة من بريدك أولًا'});const password=req.body.password;if(typeof password!=='string'||password.length<8||password.length>128)return res.status(400).json({error:'كلمة المرور من 8 إلى 128 حرفًا'});const token=unseal(recovery.token).access_token;await sb.identity(token);await sb.request('/user',{password},token,'PUT');delete req.session.passwordRecovery;await new Promise((resolve,reject)=>req.session.save(e=>e?reject(e):resolve()));res.json({ok:true,message:'اتغيرت كلمة المرور. سجل الدخول بالكلمة الجديدة.'});}));
module.exports=router;
