'use strict';
const {run}=require('./db');
const seeds=[
 {slug:'write-an-application',category:'Writing',title_ar:'رسالة تقديم قصيرة تشبهك',title_en:'Write an application that sounds like you',excerpt_ar:'سبب واضح للتواصل، خبرة مناسبة، وطلب بسيط في آخر الرسالة.',excerpt_en:'A clear reason, relevant experience and a simple next step.',body_ar:'ابدأ بسبب التواصل\n\nهل تقدم على وظيفة معلنة أم تسأل عن فرصة مناسبة؟ وضح الهدف في أول سطر، ولا تفترض وجود وظيفة لم تعلنها الشركة.\n\nاختار معلومات حقيقية\n\nاستخدم نقطة أو نقطتين من سيرتك لهما علاقة بالمجال. اذكر مثالًا عمليًا إن وجد. لا تضف خبرة أو مهارة لأن الـAI اقترحها.\n\nخلّي الأسلوب أسلوبك\n\nفي إعدادات الكتابة، اختار اللغة والنبرة والطول واكتب مثالًا قصيرًا من كلامك. وضح الكلمات التي لا تحب استخدامها. اقرأ المسودة بصوتك وعدل أي جملة لا تقولها عادة.\n\nراجع قبل الإرسال\n\nراجع اسم الشركة والبريد والمرفق. جرّب الإرسال لنفسك. اختم بسؤال بسيط عن الخطوة المناسبة، دون وعود أو ضغط على المستلم.',body_en:'State your purpose\n\nAre you applying for an advertised role or asking about a suitable opportunity? Say so upfront. Do not imply an opening exists unless you know it does.\n\nUse real experience\n\nChoose one or two relevant facts from your CV. Add a practical example where possible. Do not adopt a skill or claim simply because AI suggested it.\n\nKeep your voice\n\nIn writing settings, choose language, tone and length, and add a short sample of your own writing. List phrases you prefer to avoid. Read the draft aloud and change sentences you would not normally say.\n\nReview before sending\n\nCheck the company, recipient and attachment. Send a test to yourself. Finish with a simple next-step question without pressure or promises.'},
 {slug:'prepare-company-sheet',category:'Data',title_ar:'جهّز شيت الشركات للاستيراد',title_en:'Prepare your company sheet',excerpt_ar:'أعمدة واضحة وأرقام محفوظة كنص لتقليل أخطاء الاستيراد.',excerpt_en:'Clear columns and phone numbers stored as text help prevent import errors.',body_ar:'رتب الأعمدة\n\nفي أول ورقة، اجعل أول صف عناوين: اسم الشركة، الإيميل، الهاتف، المجال، الموقع. كل صف بعده شركة واحدة. الاسم ووسيلة تواصل واحدة على الأقل مطلوبان.\n\nاحفظ الهاتف كنص\n\nاضبط عمود الهاتف على Text قبل إدخال الرقم. استخدم كود الدولة، وتجنب الصيغ الحسابية والخلايا المدمجة. راجع البريد بحثًا عن مسافات وأخطاء كتابة.\n\nارفع ثم طابق\n\nاختار الملف داخل الشركات، ثم طابق كل حقل بعموده وأكد الاستيراد. رفع الملف وحده يعرض الأعمدة ولا يضيف الشركات بعد. راجع عدد المضاف والمتخطى ثم فلاتر القائمة.\n\nاختار قناة الإرسال\n\nشركة لها بريد فقط يمكن مراسلتها بالإيميل. عند اختيار واتساب، الشركات دون هاتف تتخطى بسبب واضح، ولا تتحول للإيميل تلقائيًا.',body_en:'Organise the columns\n\nOn the first sheet, use headers for company name, email, phone, field and location. Each subsequent row is one company. A name and at least one contact method are required.\n\nKeep phones as text\n\nSet the phone column to Text before entering numbers. Include the country code. Avoid formulas and merged cells, and check emails for spaces or typos.\n\nUpload and map\n\nUpload from Companies, map the columns and confirm import. Uploading alone previews the headers; it does not yet add companies. Review added and skipped counts, then check the list filters.\n\nChoose the channel\n\nAn email-only company can receive email. When WhatsApp is selected, companies without a phone are skipped with a reason rather than automatically switched to email.'},
 {slug:'choose-your-channel',category:'Channels',title_ar:'إيميل ولا واتساب؟ اختار حسب الشركة',title_en:'Email or WhatsApp? Choose for the company',excerpt_ar:'القناة المناسبة تبدأ بوسيلة تواصل نشرتها الشركة وبيانات راجعتها.',excerpt_en:'Start with a contact channel the company has provided and details you have checked.',body_ar:'اختار وسيلة مناسبة\n\nاستخدم وسائل التواصل التي وفرتها الشركة للتقديم. البريد مناسب لعنوان واضح ورسالة ومرفق. لا تعتبر وجود رقم هاتف موافقة على استقبال رسائل تقديم متكررة.\n\nاربط حسابك\n\nاربط Gmail بزر Google واختار حساب الإرسال إذا ربطت أكثر من حساب. للواتساب، افتح قنوات التواصل واربط حسابك من هاتفك وفق الخطوات الظاهرة.\n\nراجع المستلمين\n\nحدد قناة الدفعة أو الرسالة، وراجع بيانات الشركات. البيانات الناقصة تؤدي لتخطي الشركة على هذه القناة. جرّب برسالة واحدة إلى حساب تملكه قبل إرسال دفعة.\n\nافهم التقارير\n\nنجاح الإرسال لا يعني قراءة الرسالة أو الرد. مؤشرات القراءة قد تكون غير متاحة أو غير دقيقة بسبب إعدادات الخصوصية. راجع حالة الإرسال والأخطاء والردود المرصودة ولا تكرر رسالة فاشلة قبل فهم السبب.',body_en:'Choose an appropriate channel\n\nUse contact channels the company has provided for applications. Email supports a clear subject and attachment. A published phone number is not permission for repeated unsolicited applications.\n\nConnect your account\n\nConnect Gmail with Google and choose a sender if you have multiple accounts. For WhatsApp, open communication channels and follow the on-screen linking steps on your phone.\n\nReview recipients\n\nChoose a channel for the batch or individual message and check contact details. Missing details cause a skip on that channel. Test with one message to an account you own before sending a batch.\n\nUnderstand reports\n\nSent does not mean read or replied. Read signals can be unavailable or unreliable because of privacy settings. Review send status, errors and detected replies before retrying a failed message.'}
];
async function ensureWebsiteSchema(){await run(`
ALTER TABLE users ADD COLUMN IF NOT EXISTS suspended_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS suspension_reason TEXT;
CREATE TABLE IF NOT EXISTS website_posts(id TEXT PRIMARY KEY,slug TEXT UNIQUE NOT NULL,title_ar TEXT NOT NULL,title_en TEXT NOT NULL,excerpt_ar TEXT NOT NULL,excerpt_en TEXT NOT NULL,body_ar TEXT NOT NULL,body_en TEXT NOT NULL,category TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'draft',published_at TIMESTAMPTZ,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS website_settings(id INTEGER PRIMARY KEY CHECK(id=1),tool_paused BOOLEAN NOT NULL DEFAULT FALSE,notice TEXT NOT NULL DEFAULT '');
INSERT INTO website_settings(id) VALUES(1) ON CONFLICT(id) DO NOTHING;
CREATE TABLE IF NOT EXISTS admin_audit(id BIGSERIAL PRIMARY KEY,actor_id TEXT NOT NULL REFERENCES users(id),action TEXT NOT NULL,target_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
`);for(const s of seeds)await run(`INSERT INTO website_posts(id,slug,category,title_ar,title_en,excerpt_ar,excerpt_en,body_ar,body_en,status,published_at) VALUES($1,$1,$2,$3,$4,$5,$6,$7,$8,'published',NOW()) ON CONFLICT(slug) DO NOTHING`,[s.slug,s.category,s.title_ar,s.title_en,s.excerpt_ar,s.excerpt_en,s.body_ar,s.body_en]);}
module.exports={ensureWebsiteSchema,seeds};
